/**
  * \file      DriverSections.cpp
  * \brief     Registration of driver files for creation and usage of XBOX
  *             loadable sections
  *
  * \note      This file is autogenerated via Sectionize.pl DO NOT EDIT!
  */

//= I N C L U D E S ====================================================
#include <Xtl.h>
#include <stdio.h>
#include <map>
#include <string>
#include "MAMEoX.h"
#include "DebugLogger.h"
extern "C" {
#include "osd_cpu.h"
}
//= D E F I N E S ======================================================
#define DATA_PREFIX      "D"
#define CODE_PREFIX      "C"
#define BSS_PREFIX       "B"
#define CONST_PREFIX     "K"

//= G L O B A L = V A R S ==============================================
static std::map< std::string, std::string >  g_nameToSectionMap;
//= F U N C T I O N S ==================================================

#ifdef _DEBUG
//-------------------------------------------------------------
//	CheckDriverSectionRAM
//-------------------------------------------------------------
void CheckDriverSectionRAM( void )
{
  std::map< std::string, std::string >::iterator i = g_nameToSectionMap.begin();
  for( ; i != g_nameToSectionMap.end(); ++i )
  {
    std::string sectionName;
    sectionName = CODE_PREFIX;
    sectionName += (*i).second.c_str();
    HANDLE h = XGetSectionHandle( sectionName.c_str() );
    if( h != INVALID_HANDLE_VALUE )
    {
      UINT32 sz = XGetSectionSize( h );
      PRINTMSG( T_INFO, "Driver %s [CODE]: %lu", (*i).first.c_str(), sz );
    }
    else
      PRINTMSG( T_ERROR, "Invalid section %s for file %s!", (*i).second.c_str(), (*i).first.c_str() );

    sectionName = DATA_PREFIX;
    sectionName += (*i).second.c_str();
    h = XGetSectionHandle( sectionName.c_str() );
    if( h != INVALID_HANDLE_VALUE )
    {
      UINT32 sz = XGetSectionSize( h );
      PRINTMSG( T_INFO, "Driver %s [DATA]: %lu", (*i).first.c_str(), sz );
    }
    else
      PRINTMSG( T_ERROR, "Invalid section %s for file %s!", (*i).second.c_str(), (*i).first.c_str() );

    sectionName = BSS_PREFIX;
    sectionName += (*i).second.c_str();
    h = XGetSectionHandle( sectionName.c_str() );
    if( h != INVALID_HANDLE_VALUE )
    {
      UINT32 sz = XGetSectionSize( h );
      PRINTMSG( T_INFO, "Driver %s [BSS]: %lu", (*i).first.c_str(), sz );
    }
    else
    {
      PRINTMSG( T_ERROR, "Invalid section %s for file %s!", (*i).second.c_str(), (*i).first.c_str() );
    }

    sectionName = CONST_PREFIX;
    sectionName += (*i).second.c_str();
    h = XGetSectionHandle( sectionName.c_str() );
    if( h != INVALID_HANDLE_VALUE )
    {
      UINT32 sz = XGetSectionSize( h );
      PRINTMSG( T_INFO, "Driver %s [CONST]: %lu", (*i).first.c_str(), sz );
    }
    else
      PRINTMSG( T_ERROR, "Invalid section %s for file %s!", (*i).second.c_str(), (*i).first.c_str() );

    DebugLoggerFlush();
  }
}
#endif


//-------------------------------------------------------------
//	RegisterSectionName
//-------------------------------------------------------------
static void RegisterSectionName( const char *DriverFileName, const char *DataSectionName )
{
    // Add the section name to the map
  g_nameToSectionMap[ DriverFileName ] = DataSectionName;
}


//-------------------------------------------------------------
//	LoadDriverSectionByName
//-------------------------------------------------------------
BOOL LoadDriverSectionByName( const char *DriverFileName )
{
  std::map< std::string, std::string >::iterator i = g_nameToSectionMap.find( DriverFileName );
  if( i == g_nameToSectionMap.end() )
    return FALSE;
  std::string sectionName;
  void *addr;
  sectionName = DATA_PREFIX;
  sectionName += (*i).second.c_str();
  addr = XLoadSection( sectionName.c_str() );
  if( !addr )
  {
    UINT32 lastErr = GetLastError();
    PRINTMSG( T_ERROR, "XLoadSection failed! 0x%X\r\n", lastErr );
    //osd_print_error( "Failed to load section %s!", sectionName.c_str() );
    //return FALSE;
  }

  sectionName = CODE_PREFIX;
  sectionName += (*i).second.c_str();
  addr = XLoadSection( sectionName.c_str() );
  if( !addr )
  {
    UINT32 lastErr = GetLastError();
    PRINTMSG( T_ERROR, "XLoadSection failed! 0x%X\r\n", lastErr );
    //osd_print_error( "Failed to load section %s!", sectionName.c_str() );
    //return FALSE;
  }

  sectionName = BSS_PREFIX;
  sectionName += (*i).second.c_str();
  addr = XLoadSection( sectionName.c_str() );
  if( !addr )
  {
    UINT32 lastErr = GetLastError();
    PRINTMSG( T_ERROR, "XLoadSection failed! 0x%X\r\n", lastErr );
    //osd_print_error( "Failed to load section %s!", sectionName.c_str() );
    //return FALSE;
  }

  sectionName = CONST_PREFIX;
  sectionName += (*i).second.c_str();
  addr = XLoadSection( sectionName.c_str() );
  if( !addr )
  {
    UINT32 lastErr = GetLastError();
    PRINTMSG( T_ERROR, "XLoadSection failed! 0x%X\r\n", lastErr );
    //osd_print_error( "Failed to load section %s!", sectionName.c_str() );
    //return FALSE;
  }
  return TRUE;
}


//-------------------------------------------------------------
//	UnloadDriverSectionByName
//-------------------------------------------------------------
BOOL UnloadDriverSectionByName( const char *DriverFileName )
{
  std::map< std::string, std::string >::iterator i = g_nameToSectionMap.find( DriverFileName );
  if( i == g_nameToSectionMap.end() )
    return FALSE;
  BOOL dataRet, codeRet, bssRet, constRet;
  std::string sectionName;
  sectionName = DATA_PREFIX;
  sectionName += (*i).second.c_str();
  dataRet = XFreeSection( sectionName.c_str() );

  sectionName = CODE_PREFIX;
  sectionName += (*i).second.c_str();
  codeRet = XFreeSection( sectionName.c_str() );

  sectionName = BSS_PREFIX;
  sectionName += (*i).second.c_str();
  bssRet = XFreeSection( sectionName.c_str() );

  sectionName = CONST_PREFIX;
  sectionName += (*i).second.c_str();
  constRet = XFreeSection( sectionName.c_str() );

  return (dataRet && codeRet && bssRet && constRet);
}


//-------------------------------------------------------------
//	LoadDriverDataSections
//-------------------------------------------------------------
BOOL LoadDriverDataSections( void )
{
  std::map< std::string, std::string >::iterator i = g_nameToSectionMap.begin();
  for( ; i != g_nameToSectionMap.end(); ++i )
  {
    std::string sectionName;
    sectionName = DATA_PREFIX;
    sectionName += (*i).second.c_str();
    if( !XLoadSection( sectionName.c_str() ) )
    {
      PRINTMSG( T_ERROR, "Failed to load section %s!", sectionName.c_str() );
      //return FALSE;
    }

    sectionName = CONST_PREFIX;
    sectionName += (*i).second.c_str();
    if( !XLoadSection( sectionName.c_str() ) )
    {
      PRINTMSG( T_ERROR, "Failed to load section %s!", sectionName.c_str() );
      //return FALSE;
    }
  }
  return TRUE;
}


//-------------------------------------------------------------
//	UnloadDriverNonDataSections
//-------------------------------------------------------------
BOOL UnloadDriverNonDataSections( void )
{
  std::map< std::string, std::string >::iterator i = g_nameToSectionMap.begin();
  for( ; i != g_nameToSectionMap.end(); ++i )
  {
    std::string sectionName;
    sectionName = CODE_PREFIX;
    sectionName += (*i).second.c_str();
    HANDLE h = XGetSectionHandle( sectionName.c_str() );
    if( h != INVALID_HANDLE_VALUE )
      XFreeSectionByHandle( h );

    sectionName = BSS_PREFIX;
    sectionName += (*i).second.c_str();
    h = XGetSectionHandle( sectionName.c_str() );
    if( h != INVALID_HANDLE_VALUE )
      XFreeSectionByHandle( h );

  }
  return TRUE;
}


//-------------------------------------------------------------
//	UnloadDriverDataSections
//-------------------------------------------------------------
BOOL UnloadDriverDataSections( void )
{
  std::map< std::string, std::string >::iterator i = g_nameToSectionMap.begin();
  for( ; i != g_nameToSectionMap.end(); ++i )
  {
    std::string sectionName;
    sectionName = DATA_PREFIX;
    sectionName += (*i).second.c_str();
    HANDLE h = XGetSectionHandle( sectionName.c_str() );
    if( h != INVALID_HANDLE_VALUE )
      XFreeSectionByHandle( h );

    sectionName = CONST_PREFIX;
    sectionName += (*i).second.c_str();
    h = XGetSectionHandle( sectionName.c_str() );
    if( h != INVALID_HANDLE_VALUE )
      XFreeSectionByHandle( h );
  }
  return TRUE;
}


//-------------------------------------------------------------
//	RegisterDriverSectionNames
//-------------------------------------------------------------
void RegisterDriverSectionNames( void )
{
  RegisterSectionName( "src\\drivers\\1942.c", "0" );
  RegisterSectionName( "src\\drivers\\1943.c", "1" );
  RegisterSectionName( "src\\drivers\\40love.c", "2" );
  RegisterSectionName( "src\\drivers\\4enraya.c", "3" );
  RegisterSectionName( "src\\drivers\\8080bw.c", "4" );
  RegisterSectionName( "src\\drivers\\88games.c", "5" );
  RegisterSectionName( "src\\drivers\\aburner.c", "6" );
  RegisterSectionName( "src\\drivers\\ace.c", "7" );
  RegisterSectionName( "src\\drivers\\actfancr.c", "8" );
  RegisterSectionName( "src\\drivers\\aeroboto.c", "9" );
  RegisterSectionName( "src\\drivers\\aerofgt.c", "10" );
  RegisterSectionName( "src\\drivers\\afega.c", "11" );
  RegisterSectionName( "src\\drivers\\airbustr.c", "12" );
  RegisterSectionName( "src\\drivers\\ajax.c", "13" );
  RegisterSectionName( "src\\drivers\\aliens.c", "14" );
  RegisterSectionName( "src\\drivers\\alpha68k.c", "15" );
  RegisterSectionName( "src\\drivers\\ambush.c", "16" );
  RegisterSectionName( "src\\drivers\\amidar.c", "17" );
  RegisterSectionName( "src\\drivers\\amspdwy.c", "18" );
  RegisterSectionName( "src\\drivers\\angelkds.c", "19" );
  RegisterSectionName( "src\\drivers\\appoooh.c", "20" );
  RegisterSectionName( "src\\drivers\\aquarium.c", "21" );
  RegisterSectionName( "src\\drivers\\arabian.c", "22" );
  RegisterSectionName( "src\\drivers\\arcadecl.c", "23" );
  RegisterSectionName( "src\\drivers\\argus.c", "24" );
  RegisterSectionName( "src\\drivers\\arkanoid.c", "25" );
  RegisterSectionName( "src\\drivers\\armedf.c", "26" );
  RegisterSectionName( "src\\drivers\\artmagic.c", "27" );
  RegisterSectionName( "src\\drivers\\asterix.c", "28" );
  RegisterSectionName( "src\\drivers\\asteroid.c", "29" );
  RegisterSectionName( "src\\drivers\\astinvad.c", "30" );
  RegisterSectionName( "src\\drivers\\astrocde.c", "31" );
  RegisterSectionName( "src\\drivers\\astrof.c", "32" );
  RegisterSectionName( "src\\drivers\\asuka.c", "33" );
  RegisterSectionName( "src\\drivers\\atarifb.c", "34" );
  RegisterSectionName( "src\\drivers\\atarig1.c", "35" );
  RegisterSectionName( "src\\drivers\\atarig42.c", "36" );
  RegisterSectionName( "src\\drivers\\atarigt.c", "37" );
  RegisterSectionName( "src\\drivers\\atarigx2.c", "38" );
  RegisterSectionName( "src\\drivers\\atarisy1.c", "39" );
  RegisterSectionName( "src\\drivers\\atarisy2.c", "40" );
  RegisterSectionName( "src\\drivers\\ataxx.c", "41" );
  RegisterSectionName( "src\\drivers\\atetris.c", "42" );
  RegisterSectionName( "src\\drivers\\avalnche.c", "43" );
  RegisterSectionName( "src\\drivers\\avengrgs.c", "44" );
  RegisterSectionName( "src\\drivers\\aztarac.c", "45" );
  RegisterSectionName( "src\\drivers\\badlands.c", "46" );
  RegisterSectionName( "src\\drivers\\bagman.c", "47" );
  RegisterSectionName( "src\\drivers\\balsente.c", "48" );
  RegisterSectionName( "src\\drivers\\bankp.c", "49" );
  RegisterSectionName( "src\\drivers\\baraduke.c", "50" );
  RegisterSectionName( "src\\drivers\\batman.c", "51" );
  RegisterSectionName( "src\\drivers\\battlane.c", "52" );
  RegisterSectionName( "src\\drivers\\battlera.c", "53" );
  RegisterSectionName( "src\\drivers\\battlex.c", "54" );
  RegisterSectionName( "src\\drivers\\battlnts.c", "55" );
  RegisterSectionName( "src\\drivers\\bbusters.c", "56" );
  RegisterSectionName( "src\\drivers\\beaminv.c", "57" );
  RegisterSectionName( "src\\drivers\\beathead.c", "58" );
  RegisterSectionName( "src\\drivers\\beezer.c", "59" );
  RegisterSectionName( "src\\drivers\\berzerk.c", "60" );
  RegisterSectionName( "src\\drivers\\bigstrkb.c", "61" );
  RegisterSectionName( "src\\drivers\\bionicc.c", "62" );
  RegisterSectionName( "src\\drivers\\bking2.c", "63" );
  RegisterSectionName( "src\\drivers\\bladestl.c", "64" );
  RegisterSectionName( "src\\drivers\\blktiger.c", "65" );
  RegisterSectionName( "src\\drivers\\blmbycar.c", "66" );
  RegisterSectionName( "src\\drivers\\blockade.c", "67" );
  RegisterSectionName( "src\\drivers\\blockhl.c", "68" );
  RegisterSectionName( "src\\drivers\\blockout.c", "69" );
  RegisterSectionName( "src\\drivers\\bloodbro.c", "70" );
  RegisterSectionName( "src\\drivers\\blstroid.c", "71" );
  RegisterSectionName( "src\\drivers\\blueprnt.c", "72" );
  RegisterSectionName( "src\\drivers\\bogeyman.c", "73" );
  RegisterSectionName( "src\\drivers\\bombjack.c", "74" );
  RegisterSectionName( "src\\drivers\\bosco.c", "75" );
  RegisterSectionName( "src\\drivers\\bottom9.c", "76" );
  RegisterSectionName( "src\\drivers\\brkthru.c", "77" );
  RegisterSectionName( "src\\drivers\\bsktball.c", "78" );
  RegisterSectionName( "src\\drivers\\btime.c", "79" );
  RegisterSectionName( "src\\drivers\\btoads.c", "80" );
  RegisterSectionName( "src\\drivers\\bublbobl.c", "81" );
  RegisterSectionName( "src\\drivers\\buggychl.c", "82" );
  RegisterSectionName( "src\\drivers\\bwidow.c", "83" );
  RegisterSectionName( "src\\drivers\\bwing.c", "84" );
  RegisterSectionName( "src\\drivers\\bzone.c", "637" );
  RegisterSectionName( "src\\drivers\\cabal.c", "637" );
  RegisterSectionName( "src\\drivers\\canyon.c", "637" );
  RegisterSectionName( "src\\drivers\\capbowl.c", "637" );
  RegisterSectionName( "src\\drivers\\carjmbre.c", "637" );
  RegisterSectionName( "src\\drivers\\carpolo.c", "637" );
  RegisterSectionName( "src\\drivers\\cave.c", "637" );
  RegisterSectionName( "src\\drivers\\cbasebal.c", "637" );
  RegisterSectionName( "src\\drivers\\cbuster.c", "637" );
  RegisterSectionName( "src\\drivers\\ccastles.c", "637" );
  RegisterSectionName( "src\\drivers\\cchasm.c", "637" );
  RegisterSectionName( "src\\drivers\\cclimber.c", "637" );
  RegisterSectionName( "src\\drivers\\centiped.c", "637" );
  RegisterSectionName( "src\\drivers\\chaknpop.c", "637" );
  RegisterSectionName( "src\\drivers\\champbas.c", "638" );
  RegisterSectionName( "src\\drivers\\cheekyms.c", "638" );
  RegisterSectionName( "src\\drivers\\chinagat.c", "638" );
  RegisterSectionName( "src\\drivers\\chindrag.c", "638" );
  RegisterSectionName( "src\\drivers\\chqflag.c", "639" );
  RegisterSectionName( "src\\drivers\\cinemat.c", "639" );
  RegisterSectionName( "src\\drivers\\circus.c", "639" );
  RegisterSectionName( "src\\drivers\\circusc.c", "639" );
  RegisterSectionName( "src\\drivers\\cischeat.c", "639" );
  RegisterSectionName( "src\\drivers\\citycon.c", "639" );
  RegisterSectionName( "src\\drivers\\clayshoo.c", "639" );
  RegisterSectionName( "src\\drivers\\cloak.c", "639" );
  RegisterSectionName( "src\\drivers\\cloud9.c", "639" );
  RegisterSectionName( "src\\drivers\\clshroad.c", "639" );
  RegisterSectionName( "src\\drivers\\cninja.c", "639" );
  RegisterSectionName( "src\\drivers\\cojag.c", "639" );
  RegisterSectionName( "src\\drivers\\combatsc.c", "639" );
  RegisterSectionName( "src\\drivers\\commando.c", "639" );
  RegisterSectionName( "src\\drivers\\congo.c", "639" );
  RegisterSectionName( "src\\drivers\\contra.c", "639" );
  RegisterSectionName( "src\\drivers\\coolpool.c", "639" );
  RegisterSectionName( "src\\drivers\\cop01.c", "639" );
  RegisterSectionName( "src\\drivers\\copsnrob.c", "639" );
  RegisterSectionName( "src\\drivers\\cosmic.c", "639" );
  RegisterSectionName( "src\\drivers\\cps1.c", "639" );
  RegisterSectionName( "src\\drivers\\cps2.c", "639" );
  RegisterSectionName( "src\\drivers\\crbaloon.c", "639" );
  RegisterSectionName( "src\\drivers\\crgolf.c", "639" );
  RegisterSectionName( "src\\drivers\\crimfght.c", "639" );
  RegisterSectionName( "src\\drivers\\crshrace.c", "639" );
  RegisterSectionName( "src\\drivers\\cshooter.c", "639" );
  RegisterSectionName( "src\\drivers\\cvs.c", "639" );
  RegisterSectionName( "src\\drivers\\cyberbal.c", "639" );
  RegisterSectionName( "src\\drivers\\darius.c", "639" );
  RegisterSectionName( "src\\drivers\\darkseal.c", "639" );
  RegisterSectionName( "src\\drivers\\dassault.c", "639" );
  RegisterSectionName( "src\\drivers\\dbz2.c", "639" );
  RegisterSectionName( "src\\drivers\\dcon.c", "639" );
  RegisterSectionName( "src\\drivers\\dday.c", "639" );
  RegisterSectionName( "src\\drivers\\ddenlovr.c", "639" );
  RegisterSectionName( "src\\drivers\\ddragon.c", "639" );
  RegisterSectionName( "src\\drivers\\ddragon3.c", "639" );
  RegisterSectionName( "src\\drivers\\ddrible.c", "639" );
  RegisterSectionName( "src\\drivers\\deadang.c", "639" );
  RegisterSectionName( "src\\drivers\\dec0.c", "639" );
  RegisterSectionName( "src\\drivers\\dec8.c", "639" );
  RegisterSectionName( "src\\drivers\\deco32.c", "639" );
  RegisterSectionName( "src\\drivers\\decocass.c", "639" );
  RegisterSectionName( "src\\drivers\\deniam.c", "639" );
  RegisterSectionName( "src\\drivers\\destroyr.c", "639" );
  RegisterSectionName( "src\\drivers\\digdug.c", "639" );
  RegisterSectionName( "src\\drivers\\diverboy.c", "639" );
  RegisterSectionName( "src\\drivers\\dkong.c", "639" );
  RegisterSectionName( "src\\drivers\\dlair.c", "639" );
  RegisterSectionName( "src\\drivers\\docastle.c", "639" );
  RegisterSectionName( "src\\drivers\\dogfgt.c", "639" );
  RegisterSectionName( "src\\drivers\\dominos.c", "639" );
  RegisterSectionName( "src\\drivers\\dooyong.c", "639" );
  RegisterSectionName( "src\\drivers\\dotrikun.c", "639" );
  RegisterSectionName( "src\\drivers\\dragrace.c", "639" );
  RegisterSectionName( "src\\drivers\\drgnmst.c", "639" );
  RegisterSectionName( "src\\drivers\\dribling.c", "639" );
  RegisterSectionName( "src\\drivers\\drmicro.c", "639" );
  RegisterSectionName( "src\\drivers\\dynax.c", "639" );
  RegisterSectionName( "src\\drivers\\dynduke.c", "639" );
  RegisterSectionName( "src\\drivers\\epos.c", "639" );
  RegisterSectionName( "src\\drivers\\eprom.c", "639" );
  RegisterSectionName( "src\\drivers\\equites.c", "639" );
  RegisterSectionName( "src\\drivers\\esd16.c", "639" );
  RegisterSectionName( "src\\drivers\\espial.c", "639" );
  RegisterSectionName( "src\\drivers\\exctsccr.c", "639" );
  RegisterSectionName( "src\\drivers\\exedexes.c", "639" );
  RegisterSectionName( "src\\drivers\\exerion.c", "639" );
  RegisterSectionName( "src\\drivers\\exidy.c", "639" );
  RegisterSectionName( "src\\drivers\\exidy440.c", "639" );
  RegisterSectionName( "src\\drivers\\exprraid.c", "639" );
  RegisterSectionName( "src\\drivers\\exterm.c", "639" );
  RegisterSectionName( "src\\drivers\\exzisus.c", "639" );
  RegisterSectionName( "src\\drivers\\f1gp.c", "639" );
  RegisterSectionName( "src\\drivers\\fantland.c", "639" );
  RegisterSectionName( "src\\drivers\\fastfred.c", "640" );
  RegisterSectionName( "src\\drivers\\fastlane.c", "640" );
  RegisterSectionName( "src\\drivers\\fcombat.c", "640" );
  RegisterSectionName( "src\\drivers\\finalizr.c", "640" );
  RegisterSectionName( "src\\drivers\\findout.c", "640" );
  RegisterSectionName( "src\\drivers\\firetrap.c", "640" );
  RegisterSectionName( "src\\drivers\\firetrk.c", "640" );
  RegisterSectionName( "src\\drivers\\fitfight.c", "640" );
  RegisterSectionName( "src\\drivers\\flkatck.c", "640" );
  RegisterSectionName( "src\\drivers\\flower.c", "640" );
  RegisterSectionName( "src\\drivers\\flstory.c", "640" );
  RegisterSectionName( "src\\drivers\\flyball.c", "640" );
  RegisterSectionName( "src\\drivers\\foodf.c", "640" );
  RegisterSectionName( "src\\drivers\\freekick.c", "640" );
  RegisterSectionName( "src\\drivers\\frogger.c", "640" );
  RegisterSectionName( "src\\drivers\\fromanc2.c", "640" );
  RegisterSectionName( "src\\drivers\\fromance.c", "640" );
  RegisterSectionName( "src\\drivers\\funkybee.c", "640" );
  RegisterSectionName( "src\\drivers\\funkyjet.c", "640" );
  RegisterSectionName( "src\\drivers\\fuuki16.c", "640" );
  RegisterSectionName( "src\\drivers\\gaelco.c", "640" );
  RegisterSectionName( "src\\drivers\\gaelco2.c", "640" );
  RegisterSectionName( "src\\drivers\\gaiden.c", "640" );
  RegisterSectionName( "src\\drivers\\galaga.c", "640" );
  RegisterSectionName( "src\\drivers\\galaxian.c", "640" );
  RegisterSectionName( "src\\drivers\\galivan.c", "640" );
  RegisterSectionName( "src\\drivers\\galpani2.c", "640" );
  RegisterSectionName( "src\\drivers\\galpanic.c", "640" );
  RegisterSectionName( "src\\drivers\\galspnbl.c", "640" );
  RegisterSectionName( "src\\drivers\\gameplan.c", "640" );
  RegisterSectionName( "src\\drivers\\gaplus.c", "640" );
  RegisterSectionName( "src\\drivers\\gauntlet.c", "640" );
  RegisterSectionName( "src\\drivers\\gberet.c", "640" );
  RegisterSectionName( "src\\drivers\\gbusters.c", "640" );
  RegisterSectionName( "src\\drivers\\gcpinbal.c", "640" );
  RegisterSectionName( "src\\drivers\\geebee.c", "640" );
  RegisterSectionName( "src\\drivers\\gijoe.c", "640" );
  RegisterSectionName( "src\\drivers\\ginganin.c", "640" );
  RegisterSectionName( "src\\drivers\\gladiatr.c", "640" );
  RegisterSectionName( "src\\drivers\\gng.c", "640" );
  RegisterSectionName( "src\\drivers\\goindol.c", "640" );
  RegisterSectionName( "src\\drivers\\gomoku.c", "640" );
  RegisterSectionName( "src\\drivers\\gotcha.c", "640" );
  RegisterSectionName( "src\\drivers\\gottlieb.c", "640" );
  RegisterSectionName( "src\\drivers\\gotya.c", "640" );
  RegisterSectionName( "src\\drivers\\gradius3.c", "640" );
  RegisterSectionName( "src\\drivers\\grchamp.c", "640" );
  RegisterSectionName( "src\\drivers\\gridlee.c", "640" );
  RegisterSectionName( "src\\drivers\\grobda.c", "640" );
  RegisterSectionName( "src\\drivers\\groundfx.c", "640" );
  RegisterSectionName( "src\\drivers\\grtwall.c", "641" );
  RegisterSectionName( "src\\drivers\\gstriker.c", "642" );
  RegisterSectionName( "src\\drivers\\gsword.c", "642" );
  RegisterSectionName( "src\\drivers\\gumbo.c", "642" );
  RegisterSectionName( "src\\drivers\\gunbustr.c", "642" );
  RegisterSectionName( "src\\drivers\\gundealr.c", "642" );
  RegisterSectionName( "src\\drivers\\gunsmoke.c", "642" );
  RegisterSectionName( "src\\drivers\\gyruss.c", "642" );
  RegisterSectionName( "src\\drivers\\hal21.c", "642" );
  RegisterSectionName( "src\\drivers\\halleys.c", "642" );
  RegisterSectionName( "src\\drivers\\hanaawas.c", "642" );
  RegisterSectionName( "src\\drivers\\hanaroku.c", "642" );
  RegisterSectionName( "src\\drivers\\harddriv.c", "642" );
  RegisterSectionName( "src\\drivers\\hcastle.c", "642" );
  RegisterSectionName( "src\\drivers\\hexa.c", "642" );
  RegisterSectionName( "src\\drivers\\hexion.c", "642" );
  RegisterSectionName( "src\\drivers\\higemaru.c", "642" );
  RegisterSectionName( "src\\drivers\\hitme.c", "642" );
  RegisterSectionName( "src\\drivers\\hnayayoi.c", "642" );
  RegisterSectionName( "src\\drivers\\holeland.c", "642" );
  RegisterSectionName( "src\\drivers\\homedata.c", "642" );
  RegisterSectionName( "src\\drivers\\hyhoo.c", "642" );
  RegisterSectionName( "src\\drivers\\hyperspt.c", "642" );
  RegisterSectionName( "src\\drivers\\hyprduel.c", "642" );
  RegisterSectionName( "src\\drivers\\ikki.c", "642" );
  RegisterSectionName( "src\\drivers\\iqblock.c", "642" );
  RegisterSectionName( "src\\drivers\\irobot.c", "642" );
  RegisterSectionName( "src\\drivers\\ironhors.c", "642" );
  RegisterSectionName( "src\\drivers\\itech32.c", "642" );
  RegisterSectionName( "src\\drivers\\itech8.c", "642" );
  RegisterSectionName( "src\\drivers\\jack.c", "642" );
  RegisterSectionName( "src\\drivers\\jackal.c", "642" );
  RegisterSectionName( "src\\drivers\\jailbrek.c", "642" );
  RegisterSectionName( "src\\drivers\\jalmah.c", "642" );
  RegisterSectionName( "src\\drivers\\jedi.c", "660" );
  RegisterSectionName( "src\\drivers\\jrpacman.c", "660" );
  RegisterSectionName( "src\\drivers\\junofrst.c", "660" );
  RegisterSectionName( "src\\drivers\\kaneko16.c", "660" );
  RegisterSectionName( "src\\drivers\\kangaroo.c", "660" );
  RegisterSectionName( "src\\drivers\\karnov.c", "660" );
  RegisterSectionName( "src\\drivers\\kchamp.c", "660" );
  RegisterSectionName( "src\\drivers\\kickgoal.c", "660" );
  RegisterSectionName( "src\\drivers\\kingobox.c", "660" );
  RegisterSectionName( "src\\drivers\\kinst.c", "660" );
  RegisterSectionName( "src\\drivers\\klax.c", "660" );
  RegisterSectionName( "src\\drivers\\kncljoe.c", "660" );
  RegisterSectionName( "src\\drivers\\konamigx.c", "660" );
  RegisterSectionName( "src\\drivers\\kopunch.c", "660" );
  RegisterSectionName( "src\\drivers\\kyugo.c", "660" );
  RegisterSectionName( "src\\drivers\\labyrunr.c", "660" );
  RegisterSectionName( "src\\drivers\\ladybug.c", "660" );
  RegisterSectionName( "src\\drivers\\lasso.c", "660" );
  RegisterSectionName( "src\\drivers\\lastduel.c", "660" );
  RegisterSectionName( "src\\drivers\\lazercmd.c", "660" );
  RegisterSectionName( "src\\drivers\\legionna.c", "660" );
  RegisterSectionName( "src\\drivers\\leland.c", "660" );
  RegisterSectionName( "src\\drivers\\lemmings.c", "660" );
  RegisterSectionName( "src\\drivers\\leprechn.c", "660" );
  RegisterSectionName( "src\\drivers\\lethalj.c", "660" );
  RegisterSectionName( "src\\drivers\\liberate.c", "660" );
  RegisterSectionName( "src\\drivers\\liberatr.c", "660" );
  RegisterSectionName( "src\\drivers\\lkage.c", "660" );
  RegisterSectionName( "src\\drivers\\locomotn.c", "660" );
  RegisterSectionName( "src\\drivers\\looping.c", "660" );
  RegisterSectionName( "src\\drivers\\lsasquad.c", "660" );
  RegisterSectionName( "src\\drivers\\lwings.c", "660" );
  RegisterSectionName( "src\\drivers\\m107.c", "660" );
  RegisterSectionName( "src\\drivers\\m62.c", "660" );
  RegisterSectionName( "src\\drivers\\m72.c", "660" );
  RegisterSectionName( "src\\drivers\\m79amb.c", "660" );
  RegisterSectionName( "src\\drivers\\m90.c", "660" );
  RegisterSectionName( "src\\drivers\\m92.c", "660" );
  RegisterSectionName( "src\\drivers\\macrossp.c", "660" );
  RegisterSectionName( "src\\drivers\\madmotor.c", "660" );
  RegisterSectionName( "src\\drivers\\magmax.c", "660" );
  RegisterSectionName( "src\\drivers\\mainevt.c", "660" );
  RegisterSectionName( "src\\drivers\\mainsnk.c", "660" );
  RegisterSectionName( "src\\drivers\\mappy.c", "660" );
  RegisterSectionName( "src\\drivers\\marineb.c", "660" );
  RegisterSectionName( "src\\drivers\\mario.c", "660" );
  RegisterSectionName( "src\\drivers\\markham.c", "660" );
  RegisterSectionName( "src\\drivers\\marvins.c", "660" );
  RegisterSectionName( "src\\drivers\\matmania.c", "660" );
  RegisterSectionName( "src\\drivers\\mayumi.c", "660" );
  RegisterSectionName( "src\\drivers\\mcatadv.c", "660" );
  RegisterSectionName( "src\\drivers\\mcr1.c", "660" );
  RegisterSectionName( "src\\drivers\\mcr2.c", "660" );
  RegisterSectionName( "src\\drivers\\mcr3.c", "660" );
  RegisterSectionName( "src\\drivers\\mcr68.c", "660" );
  RegisterSectionName( "src\\drivers\\meadows.c", "660" );
  RegisterSectionName( "src\\drivers\\megasys1.c", "660" );
  RegisterSectionName( "src\\drivers\\megazone.c", "660" );
  RegisterSectionName( "src\\drivers\\mermaid.c", "660" );
  RegisterSectionName( "src\\drivers\\metlclsh.c", "660" );
  RegisterSectionName( "src\\drivers\\metro.c", "660" );
  RegisterSectionName( "src\\drivers\\mexico86.c", "660" );
  RegisterSectionName( "src\\drivers\\mhavoc.c", "660" );
  RegisterSectionName( "src\\drivers\\midtunit.c", "660" );
  RegisterSectionName( "src\\drivers\\midvunit.c", "660" );
  RegisterSectionName( "src\\drivers\\midwunit.c", "660" );
  RegisterSectionName( "src\\drivers\\midxunit.c", "660" );
  RegisterSectionName( "src\\drivers\\midyunit.c", "660" );
  RegisterSectionName( "src\\drivers\\mikie.c", "660" );
  RegisterSectionName( "src\\drivers\\minivadr.c", "660" );
  RegisterSectionName( "src\\drivers\\missb2.c", "660" );
  RegisterSectionName( "src\\drivers\\missile.c", "660" );
  RegisterSectionName( "src\\drivers\\mitchell.c", "660" );
  RegisterSectionName( "src\\drivers\\mjkjidai.c", "660" );
  RegisterSectionName( "src\\drivers\\mjsister.c", "660" );
  RegisterSectionName( "src\\drivers\\mnight.c", "660" );
  RegisterSectionName( "src\\drivers\\mole.c", "660" );
  RegisterSectionName( "src\\drivers\\momoko.c", "660" );
  RegisterSectionName( "src\\drivers\\moo.c", "660" );
  RegisterSectionName( "src\\drivers\\mosaic.c", "660" );
  RegisterSectionName( "src\\drivers\\mouser.c", "660" );
  RegisterSectionName( "src\\drivers\\mpatrol.c", "660" );
  RegisterSectionName( "src\\drivers\\mrdo.c", "660" );
  RegisterSectionName( "src\\drivers\\mrflea.c", "660" );
  RegisterSectionName( "src\\drivers\\mrjong.c", "660" );
  RegisterSectionName( "src\\drivers\\ms32.c", "660" );
  RegisterSectionName( "src\\drivers\\msisaac.c", "660" );
  RegisterSectionName( "src\\drivers\\mugsmash.c", "660" );
  RegisterSectionName( "src\\drivers\\multi32.c", "660" );
  RegisterSectionName( "src\\drivers\\munchmo.c", "660" );
  RegisterSectionName( "src\\drivers\\mustache.c", "660" );
  RegisterSectionName( "src\\drivers\\mystston.c", "661" );
  RegisterSectionName( "src\\drivers\\mystwarr.c", "661" );
  RegisterSectionName( "src\\drivers\\namcoic.c", "661" );
  RegisterSectionName( "src\\drivers\\namcona1.c", "661" );
  RegisterSectionName( "src\\drivers\\namconb1.c", "661" );
  RegisterSectionName( "src\\drivers\\namcond1.c", "661" );
  RegisterSectionName( "src\\drivers\\namcos1.c", "661" );
  RegisterSectionName( "src\\drivers\\namcos2.c", "661" );
  RegisterSectionName( "src\\drivers\\namcos21.c", "661" );
  RegisterSectionName( "src\\drivers\\namcos22.c", "661" );
  RegisterSectionName( "src\\drivers\\namcos86.c", "661" );
  RegisterSectionName( "src\\drivers\\naughtyb.c", "661" );
  RegisterSectionName( "src\\drivers\\nbmj8688.c", "661" );
  RegisterSectionName( "src\\drivers\\nbmj8891.c", "661" );
  RegisterSectionName( "src\\drivers\\nbmj8991.c", "661" );
  RegisterSectionName( "src\\drivers\\nbmj9195.c", "661" );
  RegisterSectionName( "src\\drivers\\nemesis.c", "661" );
  RegisterSectionName( "src\\drivers\\neogeo.c", "661" );
  RegisterSectionName( "src\\drivers\\news.c", "661" );
  RegisterSectionName( "src\\drivers\\ninjakd2.c", "661" );
  RegisterSectionName( "src\\drivers\\ninjakid.c", "661" );
  RegisterSectionName( "src\\drivers\\ninjaw.c", "661" );
  RegisterSectionName( "src\\drivers\\nitedrvr.c", "661" );
  RegisterSectionName( "src\\drivers\\niyanpai.c", "661" );
  RegisterSectionName( "src\\drivers\\nmk16.c", "661" );
  RegisterSectionName( "src\\drivers\\nova2001.c", "661" );
  RegisterSectionName( "src\\drivers\\nycaptor.c", "661" );
  RegisterSectionName( "src\\drivers\\nyny.c", "661" );
  RegisterSectionName( "src\\drivers\\offtwall.c", "661" );
  RegisterSectionName( "src\\drivers\\ohmygod.c", "661" );
  RegisterSectionName( "src\\drivers\\ojankohs.c", "661" );
  RegisterSectionName( "src\\drivers\\olibochu.c", "661" );
  RegisterSectionName( "src\\drivers\\omegaf.c", "661" );
  RegisterSectionName( "src\\drivers\\omegrace.c", "661" );
  RegisterSectionName( "src\\drivers\\oneshot.c", "661" );
  RegisterSectionName( "src\\drivers\\opwolf.c", "661" );
  RegisterSectionName( "src\\drivers\\orbit.c", "661" );
  RegisterSectionName( "src\\drivers\\othldrby.c", "661" );
  RegisterSectionName( "src\\drivers\\othunder.c", "661" );
  RegisterSectionName( "src\\drivers\\outrun.c", "661" );
  RegisterSectionName( "src\\drivers\\overdriv.c", "661" );
  RegisterSectionName( "src\\drivers\\pacland.c", "661" );
  RegisterSectionName( "src\\drivers\\pacman.c", "661" );
  RegisterSectionName( "src\\drivers\\pandoras.c", "661" );
  RegisterSectionName( "src\\drivers\\paradise.c", "661" );
  RegisterSectionName( "src\\drivers\\parodius.c", "662" );
  RegisterSectionName( "src\\drivers\\pass.c", "662" );
  RegisterSectionName( "src\\drivers\\pastelgl.c", "662" );
  RegisterSectionName( "src\\drivers\\pbaction.c", "662" );
  RegisterSectionName( "src\\drivers\\pbillian.c", "662" );
  RegisterSectionName( "src\\drivers\\pcktgal.c", "662" );
  RegisterSectionName( "src\\drivers\\pengo.c", "662" );
  RegisterSectionName( "src\\drivers\\pgm.c", "662" );
  RegisterSectionName( "src\\drivers\\phoenix.c", "662" );
  RegisterSectionName( "src\\drivers\\phozon.c", "662" );
  RegisterSectionName( "src\\drivers\\pingpong.c", "662" );
  RegisterSectionName( "src\\drivers\\pipedrm.c", "662" );
  RegisterSectionName( "src\\drivers\\pirates.c", "662" );
  RegisterSectionName( "src\\drivers\\pkunwar.c", "662" );
  RegisterSectionName( "src\\drivers\\playch10.c", "662" );
  RegisterSectionName( "src\\drivers\\playmark.c", "662" );
  RegisterSectionName( "src\\drivers\\plygonet.c", "662" );
  RegisterSectionName( "src\\drivers\\polepos.c", "663" );
  RegisterSectionName( "src\\drivers\\policetr.c", "663" );
  RegisterSectionName( "src\\drivers\\polyplay.c", "663" );
  RegisterSectionName( "src\\drivers\\poolshrk.c", "663" );
  RegisterSectionName( "src\\drivers\\pooyan.c", "663" );
  RegisterSectionName( "src\\drivers\\popeye.c", "663" );
  RegisterSectionName( "src\\drivers\\popper.c", "663" );
  RegisterSectionName( "src\\drivers\\portrait.c", "663" );
  RegisterSectionName( "src\\drivers\\powerins.c", "664" );
  RegisterSectionName( "src\\drivers\\prehisle.c", "664" );
  RegisterSectionName( "src\\drivers\\psikyo.c", "664" );
  RegisterSectionName( "src\\drivers\\psikyo4.c", "664" );
  RegisterSectionName( "src\\drivers\\psikyosh.c", "664" );
  RegisterSectionName( "src\\drivers\\psychic5.c", "664" );
  RegisterSectionName( "src\\drivers\\punchout.c", "664" );
  RegisterSectionName( "src\\drivers\\pushman.c", "664" );
  RegisterSectionName( "src\\drivers\\qix.c", "664" );
  RegisterSectionName( "src\\drivers\\quantum.c", "664" );
  RegisterSectionName( "src\\drivers\\quizdna.c", "664" );
  RegisterSectionName( "src\\drivers\\raiden.c", "664" );
  RegisterSectionName( "src\\drivers\\raiden2.c", "664" );
  RegisterSectionName( "src\\drivers\\raiders5.c", "664" );
  RegisterSectionName( "src\\drivers\\rainbow.c", "664" );
  RegisterSectionName( "src\\drivers\\rallyx.c", "664" );
  RegisterSectionName( "src\\drivers\\rampart.c", "664" );
  RegisterSectionName( "src\\drivers\\rastan.c", "664" );
  RegisterSectionName( "src\\drivers\\realbrk.c", "664" );
  RegisterSectionName( "src\\drivers\\redalert.c", "664" );
  RegisterSectionName( "src\\drivers\\redclash.c", "664" );
  RegisterSectionName( "src\\drivers\\relief.c", "664" );
  RegisterSectionName( "src\\drivers\\renegade.c", "664" );
  RegisterSectionName( "src\\drivers\\retofinv.c", "664" );
  RegisterSectionName( "src\\drivers\\rmhaihai.c", "664" );
  RegisterSectionName( "src\\drivers\\rockola.c", "664" );
  RegisterSectionName( "src\\drivers\\rockrage.c", "664" );
  RegisterSectionName( "src\\drivers\\rocnrope.c", "664" );
  RegisterSectionName( "src\\drivers\\rohga.c", "664" );
  RegisterSectionName( "src\\drivers\\rollerg.c", "664" );
  RegisterSectionName( "src\\drivers\\rollrace.c", "664" );
  RegisterSectionName( "src\\drivers\\rotaryf.c", "664" );
  RegisterSectionName( "src\\drivers\\route16.c", "664" );
  RegisterSectionName( "src\\drivers\\royalmah.c", "664" );
  RegisterSectionName( "src\\drivers\\rpunch.c", "664" );
  RegisterSectionName( "src\\drivers\\rungun.c", "664" );
  RegisterSectionName( "src\\drivers\\safarir.c", "664" );
  RegisterSectionName( "src\\drivers\\sauro.c", "664" );
  RegisterSectionName( "src\\drivers\\sbasketb.c", "664" );
  RegisterSectionName( "src\\drivers\\sbrkout.c", "664" );
  RegisterSectionName( "src\\drivers\\sbugger.c", "664" );
  RegisterSectionName( "src\\drivers\\scobra.c", "664" );
  RegisterSectionName( "src\\drivers\\scramble.c", "664" );
  RegisterSectionName( "src\\drivers\\scregg.c", "664" );
  RegisterSectionName( "src\\drivers\\sega.c", "664" );
  RegisterSectionName( "src\\drivers\\segac2.c", "664" );
  RegisterSectionName( "src\\drivers\\segar.c", "664" );
  RegisterSectionName( "src\\drivers\\segasyse.c", "664" );
  RegisterSectionName( "src\\drivers\\seicross.c", "664" );
  RegisterSectionName( "src\\drivers\\senjyo.c", "664" );
  RegisterSectionName( "src\\drivers\\seta.c", "664" );
  RegisterSectionName( "src\\drivers\\seta2.c", "664" );
  RegisterSectionName( "src\\drivers\\sf1.c", "664" );
  RegisterSectionName( "src\\drivers\\sg1000a.c", "664" );
  RegisterSectionName( "src\\drivers\\sgladiat.c", "664" );
  RegisterSectionName( "src\\drivers\\shadfrce.c", "664" );
  RegisterSectionName( "src\\drivers\\shangha3.c", "664" );
  RegisterSectionName( "src\\drivers\\shanghai.c", "664" );
  RegisterSectionName( "src\\drivers\\shangkid.c", "664" );
  RegisterSectionName( "src\\drivers\\shaolins.c", "664" );
  RegisterSectionName( "src\\drivers\\sharrier.c", "664" );
  RegisterSectionName( "src\\drivers\\shisen.c", "664" );
  RegisterSectionName( "src\\drivers\\shootout.c", "664" );
  RegisterSectionName( "src\\drivers\\shougi.c", "664" );
  RegisterSectionName( "src\\drivers\\shuuz.c", "664" );
  RegisterSectionName( "src\\drivers\\sidearms.c", "664" );
  RegisterSectionName( "src\\drivers\\sidepckt.c", "664" );
  RegisterSectionName( "src\\drivers\\silkroad.c", "664" );
  RegisterSectionName( "src\\drivers\\simpsons.c", "664" );
  RegisterSectionName( "src\\drivers\\skullxbo.c", "664" );
  RegisterSectionName( "src\\drivers\\skyarmy.c", "664" );
  RegisterSectionName( "src\\drivers\\skychut.c", "664" );
  RegisterSectionName( "src\\drivers\\skydiver.c", "664" );
  RegisterSectionName( "src\\drivers\\skyfox.c", "664" );
  RegisterSectionName( "src\\drivers\\skykid.c", "664" );
  RegisterSectionName( "src\\drivers\\skyraid.c", "664" );
  RegisterSectionName( "src\\drivers\\slapfght.c", "664" );
  RegisterSectionName( "src\\drivers\\slapshot.c", "664" );
  RegisterSectionName( "src\\drivers\\snk.c", "664" );
  RegisterSectionName( "src\\drivers\\snk68.c", "664" );
  RegisterSectionName( "src\\drivers\\snowbros.c", "664" );
  RegisterSectionName( "src\\drivers\\solomon.c", "664" );
  RegisterSectionName( "src\\drivers\\sonson.c", "664" );
  RegisterSectionName( "src\\drivers\\spacefb.c", "664" );
  RegisterSectionName( "src\\drivers\\spbactn.c", "664" );
  RegisterSectionName( "src\\drivers\\spcforce.c", "664" );
  RegisterSectionName( "src\\drivers\\spdbuggy.c", "664" );
  RegisterSectionName( "src\\drivers\\spdodgeb.c", "664" );
  RegisterSectionName( "src\\drivers\\speedbal.c", "664" );
  RegisterSectionName( "src\\drivers\\speedspn.c", "664" );
  RegisterSectionName( "src\\drivers\\spiders.c", "664" );
  RegisterSectionName( "src\\drivers\\splash.c", "664" );
  RegisterSectionName( "src\\drivers\\sprcros2.c", "664" );
  RegisterSectionName( "src\\drivers\\sprint2.c", "664" );
  RegisterSectionName( "src\\drivers\\spy.c", "664" );
  RegisterSectionName( "src\\drivers\\srmp2.c", "664" );
  RegisterSectionName( "src\\drivers\\srumbler.c", "664" );
  RegisterSectionName( "src\\drivers\\sshangha.c", "664" );
  RegisterSectionName( "src\\drivers\\sslam.c", "664" );
  RegisterSectionName( "src\\drivers\\ssozumo.c", "664" );
  RegisterSectionName( "src\\drivers\\ssv.c", "664" );
  RegisterSectionName( "src\\drivers\\stactics.c", "664" );
  RegisterSectionName( "src\\drivers\\stadhero.c", "664" );
  RegisterSectionName( "src\\drivers\\starcrus.c", "664" );
  RegisterSectionName( "src\\drivers\\starfire.c", "664" );
  RegisterSectionName( "src\\drivers\\starshp1.c", "664" );
  RegisterSectionName( "src\\drivers\\starwars.c", "664" );
  RegisterSectionName( "src\\drivers\\statriv2.c", "664" );
  RegisterSectionName( "src\\drivers\\stfight.c", "664" );
  RegisterSectionName( "src\\drivers\\stlforce.c", "664" );
  RegisterSectionName( "src\\drivers\\strnskil.c", "664" );
  RegisterSectionName( "src\\drivers\\stv.c", "664" );
  RegisterSectionName( "src\\drivers\\subs.c", "664" );
  RegisterSectionName( "src\\drivers\\suna16.c", "664" );
  RegisterSectionName( "src\\drivers\\suna8.c", "664" );
  RegisterSectionName( "src\\drivers\\supbtime.c", "664" );
  RegisterSectionName( "src\\drivers\\superchs.c", "664" );
  RegisterSectionName( "src\\drivers\\superpac.c", "664" );
  RegisterSectionName( "src\\drivers\\superqix.c", "664" );
  RegisterSectionName( "src\\drivers\\suprloco.c", "664" );
  RegisterSectionName( "src\\drivers\\suprnova.c", "664" );
  RegisterSectionName( "src\\drivers\\suprslam.c", "664" );
  RegisterSectionName( "src\\drivers\\surpratk.c", "664" );
  RegisterSectionName( "src\\drivers\\system1.c", "664" );
  RegisterSectionName( "src\\drivers\\system16.c", "664" );
  RegisterSectionName( "src\\drivers\\system18.c", "664" );
  RegisterSectionName( "src\\drivers\\system24.c", "664" );
  RegisterSectionName( "src\\drivers\\system32.c", "664" );
  RegisterSectionName( "src\\drivers\\tagteam.c", "664" );
  RegisterSectionName( "src\\drivers\\tail2nos.c", "664" );
  RegisterSectionName( "src\\drivers\\taito_b.c", "664" );
  RegisterSectionName( "src\\drivers\\taito_f2.c", "664" );
  RegisterSectionName( "src\\drivers\\taito_f3.c", "664" );
  RegisterSectionName( "src\\drivers\\taito_h.c", "664" );
  RegisterSectionName( "src\\drivers\\taito_l.c", "664" );
  RegisterSectionName( "src\\drivers\\taito_x.c", "664" );
  RegisterSectionName( "src\\drivers\\taito_z.c", "664" );
  RegisterSectionName( "src\\drivers\\taitoair.c", "664" );
  RegisterSectionName( "src\\drivers\\taitosj.c", "664" );
  RegisterSectionName( "src\\drivers\\tankbatt.c", "664" );
  RegisterSectionName( "src\\drivers\\tankbust.c", "664" );
  RegisterSectionName( "src\\drivers\\taotaido.c", "664" );
  RegisterSectionName( "src\\drivers\\targeth.c", "664" );
  RegisterSectionName( "src\\drivers\\taxidrvr.c", "664" );
  RegisterSectionName( "src\\drivers\\tbowl.c", "664" );
  RegisterSectionName( "src\\drivers\\tecmo.c", "664" );
  RegisterSectionName( "src\\drivers\\tecmo16.c", "664" );
  RegisterSectionName( "src\\drivers\\tecmosys.c", "664" );
  RegisterSectionName( "src\\drivers\\tehkanwc.c", "664" );
  RegisterSectionName( "src\\drivers\\tempest.c", "664" );
  RegisterSectionName( "src\\drivers\\terracre.c", "664" );
  RegisterSectionName( "src\\drivers\\tetrisp2.c", "664" );
  RegisterSectionName( "src\\drivers\\thedeep.c", "664" );
  RegisterSectionName( "src\\drivers\\thepit.c", "664" );
  RegisterSectionName( "src\\drivers\\thief.c", "664" );
  RegisterSectionName( "src\\drivers\\thoop2.c", "664" );
  RegisterSectionName( "src\\drivers\\thunderj.c", "664" );
  RegisterSectionName( "src\\drivers\\thunderx.c", "664" );
  RegisterSectionName( "src\\drivers\\tickee.c", "664" );
  RegisterSectionName( "src\\drivers\\tigeroad.c", "664" );
  RegisterSectionName( "src\\drivers\\timelimt.c", "664" );
  RegisterSectionName( "src\\drivers\\timeplt.c", "664" );
  RegisterSectionName( "src\\drivers\\tmnt.c", "664" );
  RegisterSectionName( "src\\drivers\\tnzs.c", "664" );
  RegisterSectionName( "src\\drivers\\toaplan1.c", "664" );
  RegisterSectionName( "src\\drivers\\toaplan2.c", "664" );
  RegisterSectionName( "src\\drivers\\toki.c", "664" );
  RegisterSectionName( "src\\drivers\\toobin.c", "664" );
  RegisterSectionName( "src\\drivers\\topspeed.c", "664" );
  RegisterSectionName( "src\\drivers\\toratora.c", "664" );
  RegisterSectionName( "src\\drivers\\tourtabl.c", "664" );
  RegisterSectionName( "src\\drivers\\toypop.c", "664" );
  RegisterSectionName( "src\\drivers\\tp84.c", "664" );
  RegisterSectionName( "src\\drivers\\trackfld.c", "664" );
  RegisterSectionName( "src\\drivers\\travrusa.c", "664" );
  RegisterSectionName( "src\\drivers\\triplhnt.c", "664" );
  RegisterSectionName( "src\\drivers\\troangel.c", "664" );
  RegisterSectionName( "src\\drivers\\truco.c", "664" );
  RegisterSectionName( "src\\drivers\\tsamurai.c", "664" );
  RegisterSectionName( "src\\drivers\\ttmahjng.c", "664" );
  RegisterSectionName( "src\\drivers\\tubep.c", "664" );
  RegisterSectionName( "src\\drivers\\tugboat.c", "664" );
  RegisterSectionName( "src\\drivers\\tumblep.c", "664" );
  RegisterSectionName( "src\\drivers\\tunhunt.c", "664" );
  RegisterSectionName( "src\\drivers\\turbo.c", "664" );
  RegisterSectionName( "src\\drivers\\tutankhm.c", "664" );
  RegisterSectionName( "src\\drivers\\twin16.c", "664" );
  RegisterSectionName( "src\\drivers\\twincobr.c", "664" );
  RegisterSectionName( "src\\drivers\\ultraman.c", "664" );
  RegisterSectionName( "src\\drivers\\ultratnk.c", "664" );
  RegisterSectionName( "src\\drivers\\undrfire.c", "664" );
  RegisterSectionName( "src\\drivers\\unico.c", "664" );
  RegisterSectionName( "src\\drivers\\usgames.c", "664" );
  RegisterSectionName( "src\\drivers\\vaportra.c", "664" );
  RegisterSectionName( "src\\drivers\\vastar.c", "664" );
  RegisterSectionName( "src\\drivers\\vball.c", "664" );
  RegisterSectionName( "src\\drivers\\vendetta.c", "664" );
  RegisterSectionName( "src\\drivers\\vicdual.c", "664" );
  RegisterSectionName( "src\\drivers\\victory.c", "664" );
  RegisterSectionName( "src\\drivers\\videopin.c", "664" );
  RegisterSectionName( "src\\drivers\\vigilant.c", "664" );
  RegisterSectionName( "src\\drivers\\vindictr.c", "664" );
  RegisterSectionName( "src\\drivers\\volfied.c", "664" );
  RegisterSectionName( "src\\drivers\\vsnes.c", "664" );
  RegisterSectionName( "src\\drivers\\vulgus.c", "664" );
  RegisterSectionName( "src\\drivers\\wallc.c", "664" );
  RegisterSectionName( "src\\drivers\\wardner.c", "664" );
  RegisterSectionName( "src\\drivers\\warpwarp.c", "664" );
  RegisterSectionName( "src\\drivers\\warriorb.c", "664" );
  RegisterSectionName( "src\\drivers\\wc90.c", "664" );
  RegisterSectionName( "src\\drivers\\wc90b.c", "664" );
  RegisterSectionName( "src\\drivers\\wecleman.c", "664" );
  RegisterSectionName( "src\\drivers\\welltris.c", "664" );
  RegisterSectionName( "src\\drivers\\wgp.c", "664" );
  RegisterSectionName( "src\\drivers\\williams.c", "664" );
  RegisterSectionName( "src\\drivers\\wilytowr.c", "664" );
  RegisterSectionName( "src\\drivers\\wiping.c", "664" );
  RegisterSectionName( "src\\drivers\\wiz.c", "664" );
  RegisterSectionName( "src\\drivers\\wolfpack.c", "664" );
  RegisterSectionName( "src\\drivers\\wrally.c", "665" );
  RegisterSectionName( "src\\drivers\\wwfsstar.c", "665" );
  RegisterSectionName( "src\\drivers\\wwfwfest.c", "665" );
  RegisterSectionName( "src\\drivers\\xain.c", "665" );
  RegisterSectionName( "src\\drivers\\xevious.c", "665" );
  RegisterSectionName( "src\\drivers\\xexex.c", "665" );
  RegisterSectionName( "src\\drivers\\xmen.c", "665" );
  RegisterSectionName( "src\\drivers\\xxmissio.c", "665" );
  RegisterSectionName( "src\\drivers\\xybots.c", "665" );
  RegisterSectionName( "src\\drivers\\xyonix.c", "665" );
  RegisterSectionName( "src\\drivers\\yamato.c", "665" );
  RegisterSectionName( "src\\drivers\\yard.c", "665" );
  RegisterSectionName( "src\\drivers\\yiear.c", "665" );
  RegisterSectionName( "src\\drivers\\yunsun16.c", "665" );
  RegisterSectionName( "src\\drivers\\yunsung8.c", "665" );
  RegisterSectionName( "src\\drivers\\zac2650.c", "665" );
  RegisterSectionName( "src\\drivers\\zaccaria.c", "665" );
  RegisterSectionName( "src\\drivers\\zaxxon.c", "665" );
  RegisterSectionName( "src\\drivers\\zerozone.c", "665" );
  RegisterSectionName( "src\\drivers\\zn.c", "665" );
  RegisterSectionName( "src\\drivers\\zodiack.c", "665" );
}


