/**
  * \file      XBESectionUtil.cpp
  * \brief     Registration of Driver/CPU files for creation and usage of XBOX
  *             loadable sections
  *
  * \note      This file is autogenerated via Sectionize.pl, so any
  *               changes will probably be lost.
  */

//= I N C L U D E S ====================================================
#include "MAMEoX.h"
#include <stdio.h>
#include <map>
#include <string>
#include "DebugLogger.h"


extern "C" {
#include "osd_cpu.h"
#include "cpuintrf.h"
}


//= D E F I N E S ======================================================

struct driverSectionRegistration_t 
{
		// For some reason making these a const char, then unloading
		// the DRVSNIZE will cause a crash in retail mode. I'm not at
		// all sure exactly why this is yet, my only guess is that there
		// is something odd about how quoted constants in initializers are
		// placed into the XBE section.
  //const char *m_driverName;
  //const char *m_sectionName;
	char	m_driverName[16];
	char	m_sectionName[8];
};


#define REGISTER_DRIVERSECTION( driverName, sectionName )     { driverName, sectionName }



//= G L O B A L = V A R S ==============================================
static std::map< UINT, std::string >         g_CPUIDToSectionMap;

static BOOL																	 g_driverSectionizerLoaded = TRUE;
static BOOL																	 g_cpuSectionizerLoaded = TRUE;

//= P R O T O T Y P E S ================================================
extern "C" static void RegisterCPUSectionNames( void );


//= F U N C T I O N S ==================================================
extern "C" {

//-------------------------------------------------------------
//	InitDriverSectionizer
//-------------------------------------------------------------
void InitDriverSectionizer( void )
{
	if( !g_driverSectionizerLoaded )
	{
		if( !XLoadSection( "DRVSNIZE" ) )
		{
			PRINTMSG(( T_ERROR, "XLoadSection failed! 0x%X\r\n", GetLastError() ));
		}
		else
			g_driverSectionizerLoaded = TRUE;
	}
}


//-------------------------------------------------------------
//	TerminateDriverSectionizer
//-------------------------------------------------------------
void TerminateDriverSectionizer( void )
{
  if( !XFreeSection( "DRVSNIZE" ) )
	{
		PRINTMSG(( T_ERROR, "XFreeSection failed! 0x%X\r\n", GetLastError() ));
	}
	else
		g_driverSectionizerLoaded = FALSE;
}

//-------------------------------------------------------------
//	InitCPUSectionizer
//-------------------------------------------------------------
void InitCPUSectionizer( void )
{
  g_CPUIDToSectionMap.clear();

	if( !g_cpuSectionizerLoaded )
	{
		if( !XLoadSection( "CPUSNIZE" ) )
		{
			PRINTMSG(( T_ERROR, "XLoadSection failed! 0x%X\r\n", GetLastError() ));
		}
		else
			g_cpuSectionizerLoaded = TRUE;
	}
  RegisterCPUSectionNames();
}

//-------------------------------------------------------------
//	TerminateCPUSectionizer
//-------------------------------------------------------------
void TerminateCPUSectionizer( void )
{
  g_CPUIDToSectionMap.clear();
  if( !XFreeSection( "CPUSNIZE" ) )
	{
		PRINTMSG(( T_ERROR, "XFreeSection failed! 0x%X\r\n", GetLastError() ));
	}
	else
		g_cpuSectionizerLoaded = FALSE;
}


#pragma code_seg("DRVCSNZE")
#pragma data_seg("DRVDSNZE")
#pragma bss_seg("DRVBSNZE")
#pragma const_seg("DRVKSNZE")
#pragma comment(linker, "/merge:DRVDSNZE=DRVSNIZE")
#pragma comment(linker, "/merge:DRVCSNZE=DRVSNIZE")
#pragma comment(linker, "/merge:DRVBSNZE=DRVSNIZE")
#pragma comment(linker, "/merge:DRVKSNZE=DRVSNIZE")

#define   NUM_DRIVERSECTIONS				711
static const driverSectionRegistration_t			g_driverSectionRegistry[NUM_DRIVERSECTIONS] = { 
           REGISTER_DRIVERSECTION( "1942.c", "86" ),
           REGISTER_DRIVERSECTION( "1943.c", "87" ),
           REGISTER_DRIVERSECTION( "40love.c", "31" ),
           REGISTER_DRIVERSECTION( "4enraya.c", "89" ),
           REGISTER_DRIVERSECTION( "8080bw.c", "30" ),
           REGISTER_DRIVERSECTION( "88games.c", "91" ),
           REGISTER_DRIVERSECTION( "aburner.c", "3" ),
           REGISTER_DRIVERSECTION( "ace.c", "93" ),
           REGISTER_DRIVERSECTION( "actfancr.c", "94" ),
           REGISTER_DRIVERSECTION( "aeroboto.c", "95" ),
           REGISTER_DRIVERSECTION( "aerofgt.c", "96" ),
           REGISTER_DRIVERSECTION( "afega.c", "97" ),
           REGISTER_DRIVERSECTION( "airbustr.c", "98" ),
           REGISTER_DRIVERSECTION( "ajax.c", "99" ),
           REGISTER_DRIVERSECTION( "aliens.c", "100" ),
           REGISTER_DRIVERSECTION( "alpha68k.c", "101" ),
           REGISTER_DRIVERSECTION( "ambush.c", "102" ),
           REGISTER_DRIVERSECTION( "amidar.c", "8" ),
           REGISTER_DRIVERSECTION( "amspdwy.c", "104" ),
           REGISTER_DRIVERSECTION( "angelkds.c", "105" ),
           REGISTER_DRIVERSECTION( "appoooh.c", "106" ),
           REGISTER_DRIVERSECTION( "aquarium.c", "107" ),
           REGISTER_DRIVERSECTION( "arabian.c", "108" ),
           REGISTER_DRIVERSECTION( "arcadecl.c", "9" ),
           REGISTER_DRIVERSECTION( "argus.c", "110" ),
           REGISTER_DRIVERSECTION( "arkanoid.c", "111" ),
           REGISTER_DRIVERSECTION( "armedf.c", "112" ),
           REGISTER_DRIVERSECTION( "artmagic.c", "113" ),
           REGISTER_DRIVERSECTION( "ashnojoe.c", "114" ),
           REGISTER_DRIVERSECTION( "asterix.c", "115" ),
           REGISTER_DRIVERSECTION( "asteroid.c", "116" ),
           REGISTER_DRIVERSECTION( "astinvad.c", "117" ),
           REGISTER_DRIVERSECTION( "astrocde.c", "118" ),
           REGISTER_DRIVERSECTION( "astrof.c", "119" ),
           REGISTER_DRIVERSECTION( "asuka.c", "10" ),
           REGISTER_DRIVERSECTION( "atarifb.c", "121" ),
           REGISTER_DRIVERSECTION( "atarig1.c", "122" ),
           REGISTER_DRIVERSECTION( "atarig42.c", "123" ),
           REGISTER_DRIVERSECTION( "atarigt.c", "124" ),
           REGISTER_DRIVERSECTION( "atarigx2.c", "125" ),
           REGISTER_DRIVERSECTION( "atarisy1.c", "126" ),
           REGISTER_DRIVERSECTION( "atarisy2.c", "127" ),
           REGISTER_DRIVERSECTION( "ataxx.c", "19" ),
           REGISTER_DRIVERSECTION( "atetris.c", "129" ),
           REGISTER_DRIVERSECTION( "avalnche.c", "130" ),
           REGISTER_DRIVERSECTION( "aztarac.c", "131" ),
           REGISTER_DRIVERSECTION( "badlands.c", "132" ),
           REGISTER_DRIVERSECTION( "bagman.c", "133" ),
           REGISTER_DRIVERSECTION( "balsente.c", "134" ),
           REGISTER_DRIVERSECTION( "bankp.c", "135" ),
           REGISTER_DRIVERSECTION( "baraduke.c", "136" ),
           REGISTER_DRIVERSECTION( "batman.c", "137" ),
           REGISTER_DRIVERSECTION( "battlane.c", "138" ),
           REGISTER_DRIVERSECTION( "battlera.c", "139" ),
           REGISTER_DRIVERSECTION( "battlex.c", "140" ),
           REGISTER_DRIVERSECTION( "battlnts.c", "141" ),
           REGISTER_DRIVERSECTION( "bbusters.c", "142" ),
           REGISTER_DRIVERSECTION( "beaminv.c", "143" ),
           REGISTER_DRIVERSECTION( "beathead.c", "144" ),
           REGISTER_DRIVERSECTION( "beezer.c", "145" ),
           REGISTER_DRIVERSECTION( "berzerk.c", "146" ),
           REGISTER_DRIVERSECTION( "bigevglf.c", "147" ),
           REGISTER_DRIVERSECTION( "bigstrkb.c", "148" ),
           REGISTER_DRIVERSECTION( "bionicc.c", "149" ),
           REGISTER_DRIVERSECTION( "bishi.c", "150" ),
           REGISTER_DRIVERSECTION( "bking2.c", "151" ),
           REGISTER_DRIVERSECTION( "bladestl.c", "152" ),
           REGISTER_DRIVERSECTION( "blktiger.c", "153" ),
           REGISTER_DRIVERSECTION( "blmbycar.c", "154" ),
           REGISTER_DRIVERSECTION( "blockade.c", "155" ),
           REGISTER_DRIVERSECTION( "blockhl.c", "156" ),
           REGISTER_DRIVERSECTION( "blockout.c", "157" ),
           REGISTER_DRIVERSECTION( "bloodbro.c", "158" ),
           REGISTER_DRIVERSECTION( "blstroid.c", "159" ),
           REGISTER_DRIVERSECTION( "blueprnt.c", "160" ),
           REGISTER_DRIVERSECTION( "bogeyman.c", "161" ),
           REGISTER_DRIVERSECTION( "bombjack.c", "162" ),
           REGISTER_DRIVERSECTION( "bosco.c", "163" ),
           REGISTER_DRIVERSECTION( "bottom9.c", "164" ),
           REGISTER_DRIVERSECTION( "boxer.c", "165" ),
           REGISTER_DRIVERSECTION( "brkthru.c", "166" ),
           REGISTER_DRIVERSECTION( "bsktball.c", "167" ),
           REGISTER_DRIVERSECTION( "btime.c", "32" ),
           REGISTER_DRIVERSECTION( "btoads.c", "169" ),
           REGISTER_DRIVERSECTION( "bublbobl.c", "170" ),
           REGISTER_DRIVERSECTION( "buggychl.c", "31" ),
           REGISTER_DRIVERSECTION( "bwidow.c", "12" ),
           REGISTER_DRIVERSECTION( "bwing.c", "173" ),
           REGISTER_DRIVERSECTION( "bzone.c", "12" ),
           REGISTER_DRIVERSECTION( "cabal.c", "175" ),
           REGISTER_DRIVERSECTION( "canyon.c", "176" ),
           REGISTER_DRIVERSECTION( "capbowl.c", "177" ),
           REGISTER_DRIVERSECTION( "carjmbre.c", "178" ),
           REGISTER_DRIVERSECTION( "carpolo.c", "179" ),
           REGISTER_DRIVERSECTION( "cave.c", "180" ),
           REGISTER_DRIVERSECTION( "cbasebal.c", "181" ),
           REGISTER_DRIVERSECTION( "cbuster.c", "182" ),
           REGISTER_DRIVERSECTION( "ccastles.c", "183" ),
           REGISTER_DRIVERSECTION( "cchasm.c", "184" ),
           REGISTER_DRIVERSECTION( "cclimber.c", "8" ),
           REGISTER_DRIVERSECTION( "centiped.c", "186" ),
           REGISTER_DRIVERSECTION( "chaknpop.c", "187" ),
           REGISTER_DRIVERSECTION( "champbas.c", "188" ),
           REGISTER_DRIVERSECTION( "cheekyms.c", "189" ),
           REGISTER_DRIVERSECTION( "chinagat.c", "35" ),
           REGISTER_DRIVERSECTION( "chindrag.c", "191" ),
           REGISTER_DRIVERSECTION( "chqflag.c", "192" ),
           REGISTER_DRIVERSECTION( "cinemat.c", "193" ),
           REGISTER_DRIVERSECTION( "circus.c", "30" ),
           REGISTER_DRIVERSECTION( "circusc.c", "195" ),
           REGISTER_DRIVERSECTION( "cischeat.c", "15" ),
           REGISTER_DRIVERSECTION( "citycon.c", "197" ),
           REGISTER_DRIVERSECTION( "clayshoo.c", "198" ),
           REGISTER_DRIVERSECTION( "cloak.c", "199" ),
           REGISTER_DRIVERSECTION( "cloud9.c", "200" ),
           REGISTER_DRIVERSECTION( "clshroad.c", "29" ),
           REGISTER_DRIVERSECTION( "cninja.c", "202" ),
           REGISTER_DRIVERSECTION( "cojag.c", "203" ),
           REGISTER_DRIVERSECTION( "combatsc.c", "204" ),
           REGISTER_DRIVERSECTION( "commando.c", "205" ),
           REGISTER_DRIVERSECTION( "compgolf.c", "206" ),
           REGISTER_DRIVERSECTION( "contra.c", "207" ),
           REGISTER_DRIVERSECTION( "coolpool.c", "208" ),
           REGISTER_DRIVERSECTION( "cop01.c", "209" ),
           REGISTER_DRIVERSECTION( "copsnrob.c", "210" ),
           REGISTER_DRIVERSECTION( "cosmic.c", "211" ),
           REGISTER_DRIVERSECTION( "cps1.c", "1" ),
           REGISTER_DRIVERSECTION( "cps2.c", "1" ),
           REGISTER_DRIVERSECTION( "crbaloon.c", "214" ),
           REGISTER_DRIVERSECTION( "crgolf.c", "215" ),
           REGISTER_DRIVERSECTION( "crimfght.c", "216" ),
           REGISTER_DRIVERSECTION( "crospang.c", "217" ),
           REGISTER_DRIVERSECTION( "crshrace.c", "218" ),
           REGISTER_DRIVERSECTION( "cshooter.c", "219" ),
           REGISTER_DRIVERSECTION( "cvs.c", "220" ),
           REGISTER_DRIVERSECTION( "cyberbal.c", "221" ),
           REGISTER_DRIVERSECTION( "darius.c", "222" ),
           REGISTER_DRIVERSECTION( "darkseal.c", "223" ),
           REGISTER_DRIVERSECTION( "dassault.c", "224" ),
           REGISTER_DRIVERSECTION( "dbz2.c", "225" ),
           REGISTER_DRIVERSECTION( "dcon.c", "226" ),
           REGISTER_DRIVERSECTION( "dday.c", "227" ),
           REGISTER_DRIVERSECTION( "ddenlovr.c", "228" ),
           REGISTER_DRIVERSECTION( "ddragon.c", "35" ),
           REGISTER_DRIVERSECTION( "ddragon3.c", "230" ),
           REGISTER_DRIVERSECTION( "ddrible.c", "231" ),
           REGISTER_DRIVERSECTION( "deadang.c", "232" ),
           REGISTER_DRIVERSECTION( "dec0.c", "233" ),
           REGISTER_DRIVERSECTION( "dec8.c", "234" ),
           REGISTER_DRIVERSECTION( "deco32.c", "235" ),
           REGISTER_DRIVERSECTION( "deco_mlc.c", "236" ),
           REGISTER_DRIVERSECTION( "decocass.c", "237" ),
           REGISTER_DRIVERSECTION( "deniam.c", "238" ),
           REGISTER_DRIVERSECTION( "destroyr.c", "239" ),
           REGISTER_DRIVERSECTION( "digdug.c", "240" ),
           REGISTER_DRIVERSECTION( "diverboy.c", "241" ),
           REGISTER_DRIVERSECTION( "djboy.c", "242" ),
           REGISTER_DRIVERSECTION( "djmain.c", "243" ),
           REGISTER_DRIVERSECTION( "dkong.c", "8" ),
           REGISTER_DRIVERSECTION( "dlair.c", "245" ),
           REGISTER_DRIVERSECTION( "docastle.c", "246" ),
           REGISTER_DRIVERSECTION( "dogfgt.c", "247" ),
           REGISTER_DRIVERSECTION( "dooyong.c", "248" ),
           REGISTER_DRIVERSECTION( "dorachan.c", "249" ),
           REGISTER_DRIVERSECTION( "dotrikun.c", "250" ),
           REGISTER_DRIVERSECTION( "dragrace.c", "251" ),
           REGISTER_DRIVERSECTION( "drgnmst.c", "252" ),
           REGISTER_DRIVERSECTION( "dribling.c", "253" ),
           REGISTER_DRIVERSECTION( "drmicro.c", "254" ),
           REGISTER_DRIVERSECTION( "dynax.c", "255" ),
           REGISTER_DRIVERSECTION( "dynduke.c", "256" ),
           REGISTER_DRIVERSECTION( "embargo.c", "257" ),
           REGISTER_DRIVERSECTION( "enigma2.c", "258" ),
           REGISTER_DRIVERSECTION( "epos.c", "8" ),
           REGISTER_DRIVERSECTION( "eprom.c", "36" ),
           REGISTER_DRIVERSECTION( "equites.c", "261" ),
           REGISTER_DRIVERSECTION( "esd16.c", "262" ),
           REGISTER_DRIVERSECTION( "espial.c", "11" ),
           REGISTER_DRIVERSECTION( "exctsccr.c", "264" ),
           REGISTER_DRIVERSECTION( "exedexes.c", "265" ),
           REGISTER_DRIVERSECTION( "exerion.c", "266" ),
           REGISTER_DRIVERSECTION( "exidy.c", "17" ),
           REGISTER_DRIVERSECTION( "exidy440.c", "268" ),
           REGISTER_DRIVERSECTION( "exprraid.c", "269" ),
           REGISTER_DRIVERSECTION( "exterm.c", "14" ),
           REGISTER_DRIVERSECTION( "exzisus.c", "271" ),
           REGISTER_DRIVERSECTION( "f1gp.c", "272" ),
           REGISTER_DRIVERSECTION( "fantland.c", "273" ),
           REGISTER_DRIVERSECTION( "fastfred.c", "274" ),
           REGISTER_DRIVERSECTION( "fastlane.c", "275" ),
           REGISTER_DRIVERSECTION( "fcombat.c", "276" ),
           REGISTER_DRIVERSECTION( "finalizr.c", "277" ),
           REGISTER_DRIVERSECTION( "findout.c", "278" ),
           REGISTER_DRIVERSECTION( "firetrap.c", "279" ),
           REGISTER_DRIVERSECTION( "firetrk.c", "280" ),
           REGISTER_DRIVERSECTION( "fitfight.c", "281" ),
           REGISTER_DRIVERSECTION( "flkatck.c", "282" ),
           REGISTER_DRIVERSECTION( "flower.c", "283" ),
           REGISTER_DRIVERSECTION( "flstory.c", "284" ),
           REGISTER_DRIVERSECTION( "flyball.c", "285" ),
           REGISTER_DRIVERSECTION( "foodf.c", "286" ),
           REGISTER_DRIVERSECTION( "freekick.c", "287" ),
           REGISTER_DRIVERSECTION( "frogger.c", "8" ),
           REGISTER_DRIVERSECTION( "fromanc2.c", "289" ),
           REGISTER_DRIVERSECTION( "fromance.c", "22" ),
           REGISTER_DRIVERSECTION( "funkybee.c", "291" ),
           REGISTER_DRIVERSECTION( "funkyjet.c", "292" ),
           REGISTER_DRIVERSECTION( "funybubl.c", "293" ),
           REGISTER_DRIVERSECTION( "fuukifg2.c", "294" ),
           REGISTER_DRIVERSECTION( "fuukifg3.c", "295" ),
           REGISTER_DRIVERSECTION( "gaelco.c", "296" ),
           REGISTER_DRIVERSECTION( "gaelco2.c", "297" ),
           REGISTER_DRIVERSECTION( "gaiden.c", "298" ),
           REGISTER_DRIVERSECTION( "galaga.c", "299" ),
           REGISTER_DRIVERSECTION( "galaxian.c", "8" ),
           REGISTER_DRIVERSECTION( "galivan.c", "301" ),
           REGISTER_DRIVERSECTION( "galpani2.c", "302" ),
           REGISTER_DRIVERSECTION( "galpanic.c", "303" ),
           REGISTER_DRIVERSECTION( "galspnbl.c", "304" ),
           REGISTER_DRIVERSECTION( "gameplan.c", "305" ),
           REGISTER_DRIVERSECTION( "gaplus.c", "306" ),
           REGISTER_DRIVERSECTION( "gauntlet.c", "307" ),
           REGISTER_DRIVERSECTION( "gberet.c", "308" ),
           REGISTER_DRIVERSECTION( "gbusters.c", "309" ),
           REGISTER_DRIVERSECTION( "gcpinbal.c", "310" ),
           REGISTER_DRIVERSECTION( "gijoe.c", "311" ),
           REGISTER_DRIVERSECTION( "ginganin.c", "312" ),
           REGISTER_DRIVERSECTION( "gladiatr.c", "313" ),
           REGISTER_DRIVERSECTION( "glass.c", "314" ),
           REGISTER_DRIVERSECTION( "gng.c", "315" ),
           REGISTER_DRIVERSECTION( "goal92.c", "316" ),
           REGISTER_DRIVERSECTION( "goindol.c", "317" ),
           REGISTER_DRIVERSECTION( "gomoku.c", "318" ),
           REGISTER_DRIVERSECTION( "gotcha.c", "319" ),
           REGISTER_DRIVERSECTION( "gottlieb.c", "14" ),
           REGISTER_DRIVERSECTION( "gotya.c", "321" ),
           REGISTER_DRIVERSECTION( "gradius3.c", "322" ),
           REGISTER_DRIVERSECTION( "grchamp.c", "323" ),
           REGISTER_DRIVERSECTION( "gridlee.c", "324" ),
           REGISTER_DRIVERSECTION( "groundfx.c", "21" ),
           REGISTER_DRIVERSECTION( "grtwall.c", "326" ),
           REGISTER_DRIVERSECTION( "gstriker.c", "327" ),
           REGISTER_DRIVERSECTION( "gsword.c", "328" ),
           REGISTER_DRIVERSECTION( "gumbo.c", "329" ),
           REGISTER_DRIVERSECTION( "gunbustr.c", "21" ),
           REGISTER_DRIVERSECTION( "gundealr.c", "331" ),
           REGISTER_DRIVERSECTION( "gunsmoke.c", "332" ),
           REGISTER_DRIVERSECTION( "gyruss.c", "333" ),
           REGISTER_DRIVERSECTION( "hal21.c", "7" ),
           REGISTER_DRIVERSECTION( "halleys.c", "335" ),
           REGISTER_DRIVERSECTION( "hanaawas.c", "336" ),
           REGISTER_DRIVERSECTION( "hanaroku.c", "337" ),
           REGISTER_DRIVERSECTION( "harddriv.c", "338" ),
           REGISTER_DRIVERSECTION( "hcastle.c", "339" ),
           REGISTER_DRIVERSECTION( "hexa.c", "340" ),
           REGISTER_DRIVERSECTION( "hexion.c", "341" ),
           REGISTER_DRIVERSECTION( "higemaru.c", "342" ),
           REGISTER_DRIVERSECTION( "hitme.c", "343" ),
           REGISTER_DRIVERSECTION( "hnayayoi.c", "344" ),
           REGISTER_DRIVERSECTION( "holeland.c", "345" ),
           REGISTER_DRIVERSECTION( "homedata.c", "346" ),
           REGISTER_DRIVERSECTION( "homerun.c", "347" ),
           REGISTER_DRIVERSECTION( "hyhoo.c", "348" ),
           REGISTER_DRIVERSECTION( "hyperspt.c", "20" ),
           REGISTER_DRIVERSECTION( "hyprduel.c", "350" ),
           REGISTER_DRIVERSECTION( "ikki.c", "351" ),
           REGISTER_DRIVERSECTION( "inufuku.c", "352" ),
           REGISTER_DRIVERSECTION( "iqblock.c", "353" ),
           REGISTER_DRIVERSECTION( "irobot.c", "354" ),
           REGISTER_DRIVERSECTION( "ironhors.c", "355" ),
           REGISTER_DRIVERSECTION( "itech32.c", "356" ),
           REGISTER_DRIVERSECTION( "itech8.c", "357" ),
           REGISTER_DRIVERSECTION( "jack.c", "358" ),
           REGISTER_DRIVERSECTION( "jackal.c", "359" ),
           REGISTER_DRIVERSECTION( "jailbrek.c", "360" ),
           REGISTER_DRIVERSECTION( "jalmah.c", "361" ),
           REGISTER_DRIVERSECTION( "jchan.c", "362" ),
           REGISTER_DRIVERSECTION( "jcross.c", "363" ),
           REGISTER_DRIVERSECTION( "jedi.c", "364" ),
           REGISTER_DRIVERSECTION( "jrpacman.c", "365" ),
           REGISTER_DRIVERSECTION( "junofrst.c", "16" ),
           REGISTER_DRIVERSECTION( "kaneko16.c", "367" ),
           REGISTER_DRIVERSECTION( "kangaroo.c", "368" ),
           REGISTER_DRIVERSECTION( "karnov.c", "369" ),
           REGISTER_DRIVERSECTION( "kchamp.c", "370" ),
           REGISTER_DRIVERSECTION( "kickgoal.c", "371" ),
           REGISTER_DRIVERSECTION( "kingobox.c", "372" ),
           REGISTER_DRIVERSECTION( "kinst.c", "373" ),
           REGISTER_DRIVERSECTION( "klax.c", "374" ),
           REGISTER_DRIVERSECTION( "kncljoe.c", "375" ),
           REGISTER_DRIVERSECTION( "konamigq.c", "376" ),
           REGISTER_DRIVERSECTION( "konamigx.c", "24" ),
           REGISTER_DRIVERSECTION( "kopunch.c", "378" ),
           REGISTER_DRIVERSECTION( "kyugo.c", "379" ),
           REGISTER_DRIVERSECTION( "labyrunr.c", "380" ),
           REGISTER_DRIVERSECTION( "ladybug.c", "381" ),
           REGISTER_DRIVERSECTION( "ladyfrog.c", "382" ),
           REGISTER_DRIVERSECTION( "lasso.c", "383" ),
           REGISTER_DRIVERSECTION( "lastduel.c", "384" ),
           REGISTER_DRIVERSECTION( "lazercmd.c", "385" ),
           REGISTER_DRIVERSECTION( "legionna.c", "386" ),
           REGISTER_DRIVERSECTION( "leland.c", "19" ),
           REGISTER_DRIVERSECTION( "lemmings.c", "388" ),
           REGISTER_DRIVERSECTION( "leprechn.c", "389" ),
           REGISTER_DRIVERSECTION( "lethalj.c", "390" ),
           REGISTER_DRIVERSECTION( "liberate.c", "391" ),
           REGISTER_DRIVERSECTION( "liberatr.c", "392" ),
           REGISTER_DRIVERSECTION( "lkage.c", "393" ),
           REGISTER_DRIVERSECTION( "locomotn.c", "16" ),
           REGISTER_DRIVERSECTION( "looping.c", "395" ),
           REGISTER_DRIVERSECTION( "lsasquad.c", "396" ),
           REGISTER_DRIVERSECTION( "ltcasino.c", "397" ),
           REGISTER_DRIVERSECTION( "lwings.c", "398" ),
           REGISTER_DRIVERSECTION( "m107.c", "399" ),
           REGISTER_DRIVERSECTION( "m62.c", "400" ),
           REGISTER_DRIVERSECTION( "m72.c", "18" ),
           REGISTER_DRIVERSECTION( "m79amb.c", "402" ),
           REGISTER_DRIVERSECTION( "m90.c", "18" ),
           REGISTER_DRIVERSECTION( "m92.c", "404" ),
           REGISTER_DRIVERSECTION( "macrossp.c", "405" ),
           REGISTER_DRIVERSECTION( "madmotor.c", "406" ),
           REGISTER_DRIVERSECTION( "magmax.c", "407" ),
           REGISTER_DRIVERSECTION( "mainevt.c", "408" ),
           REGISTER_DRIVERSECTION( "mainsnk.c", "409" ),
           REGISTER_DRIVERSECTION( "malzak.c", "410" ),
           REGISTER_DRIVERSECTION( "mappy.c", "411" ),
           REGISTER_DRIVERSECTION( "marineb.c", "11" ),
           REGISTER_DRIVERSECTION( "marinedt.c", "413" ),
           REGISTER_DRIVERSECTION( "mario.c", "414" ),
           REGISTER_DRIVERSECTION( "markham.c", "415" ),
           REGISTER_DRIVERSECTION( "marvins.c", "7" ),
           REGISTER_DRIVERSECTION( "matmania.c", "417" ),
           REGISTER_DRIVERSECTION( "mayumi.c", "418" ),
           REGISTER_DRIVERSECTION( "mazerbla.c", "419" ),
           REGISTER_DRIVERSECTION( "mcatadv.c", "420" ),
           REGISTER_DRIVERSECTION( "mcr1.c", "4" ),
           REGISTER_DRIVERSECTION( "mcr2.c", "4" ),
           REGISTER_DRIVERSECTION( "mcr3.c", "4" ),
           REGISTER_DRIVERSECTION( "mcr68.c", "4" ),
           REGISTER_DRIVERSECTION( "meadows.c", "425" ),
           REGISTER_DRIVERSECTION( "megasys1.c", "15" ),
           REGISTER_DRIVERSECTION( "megazone.c", "427" ),
           REGISTER_DRIVERSECTION( "mermaid.c", "428" ),
           REGISTER_DRIVERSECTION( "metlclsh.c", "429" ),
           REGISTER_DRIVERSECTION( "metro.c", "430" ),
           REGISTER_DRIVERSECTION( "mexico86.c", "431" ),
           REGISTER_DRIVERSECTION( "mhavoc.c", "432" ),
           REGISTER_DRIVERSECTION( "midtunit.c", "4" ),
           REGISTER_DRIVERSECTION( "midvunit.c", "4" ),
           REGISTER_DRIVERSECTION( "midwunit.c", "4" ),
           REGISTER_DRIVERSECTION( "midxunit.c", "4" ),
           REGISTER_DRIVERSECTION( "midyunit.c", "4" ),
           REGISTER_DRIVERSECTION( "mikie.c", "438" ),
           REGISTER_DRIVERSECTION( "minivadr.c", "439" ),
           REGISTER_DRIVERSECTION( "missb2.c", "440" ),
           REGISTER_DRIVERSECTION( "missile.c", "441" ),
           REGISTER_DRIVERSECTION( "mitchell.c", "442" ),
           REGISTER_DRIVERSECTION( "mjkjidai.c", "443" ),
           REGISTER_DRIVERSECTION( "mjsister.c", "444" ),
           REGISTER_DRIVERSECTION( "mnight.c", "445" ),
           REGISTER_DRIVERSECTION( "mogura.c", "446" ),
           REGISTER_DRIVERSECTION( "mole.c", "447" ),
           REGISTER_DRIVERSECTION( "momoko.c", "448" ),
           REGISTER_DRIVERSECTION( "moo.c", "450" ),
           REGISTER_DRIVERSECTION( "mosaic.c", "451" ),
           REGISTER_DRIVERSECTION( "mouser.c", "452" ),
           REGISTER_DRIVERSECTION( "mpatrol.c", "6" ),
           REGISTER_DRIVERSECTION( "mrdo.c", "454" ),
           REGISTER_DRIVERSECTION( "mrflea.c", "455" ),
           REGISTER_DRIVERSECTION( "mrjong.c", "456" ),
           REGISTER_DRIVERSECTION( "ms32.c", "28" ),
           REGISTER_DRIVERSECTION( "msisaac.c", "458" ),
           REGISTER_DRIVERSECTION( "mugsmash.c", "459" ),
           REGISTER_DRIVERSECTION( "multi32.c", "3" ),
           REGISTER_DRIVERSECTION( "munchmo.c", "461" ),
           REGISTER_DRIVERSECTION( "mustache.c", "462" ),
           REGISTER_DRIVERSECTION( "mystston.c", "463" ),
           REGISTER_DRIVERSECTION( "mystwarr.c", "24" ),
           REGISTER_DRIVERSECTION( "namcoic.c", "2" ),
           REGISTER_DRIVERSECTION( "namcona1.c", "2" ),
           REGISTER_DRIVERSECTION( "namconb1.c", "2" ),
           REGISTER_DRIVERSECTION( "namcond1.c", "2" ),
           REGISTER_DRIVERSECTION( "namcos1.c", "2" ),
           REGISTER_DRIVERSECTION( "namcos10.c", "470" ),
           REGISTER_DRIVERSECTION( "namcos11.c", "2" ),
           REGISTER_DRIVERSECTION( "namcos12.c", "472" ),
           REGISTER_DRIVERSECTION( "namcos2.c", "2" ),
           REGISTER_DRIVERSECTION( "namcos21.c", "2" ),
           REGISTER_DRIVERSECTION( "namcos22.c", "2" ),
           REGISTER_DRIVERSECTION( "namcos86.c", "2" ),
           REGISTER_DRIVERSECTION( "naughtyb.c", "477" ),
           REGISTER_DRIVERSECTION( "nbmj8688.c", "478" ),
           REGISTER_DRIVERSECTION( "nbmj8891.c", "479" ),
           REGISTER_DRIVERSECTION( "nbmj8991.c", "480" ),
           REGISTER_DRIVERSECTION( "nbmj9195.c", "481" ),
           REGISTER_DRIVERSECTION( "nemesis.c", "482" ),
           REGISTER_DRIVERSECTION( "neogeo.c", "483" ),
           REGISTER_DRIVERSECTION( "news.c", "484" ),
           REGISTER_DRIVERSECTION( "ninjakd2.c", "485" ),
           REGISTER_DRIVERSECTION( "ninjakid.c", "486" ),
           REGISTER_DRIVERSECTION( "ninjaw.c", "487" ),
           REGISTER_DRIVERSECTION( "nitedrvr.c", "488" ),
           REGISTER_DRIVERSECTION( "niyanpai.c", "489" ),
           REGISTER_DRIVERSECTION( "nmk16.c", "490" ),
           REGISTER_DRIVERSECTION( "nova2001.c", "13" ),
           REGISTER_DRIVERSECTION( "nss.c", "492" ),
           REGISTER_DRIVERSECTION( "nycaptor.c", "493" ),
           REGISTER_DRIVERSECTION( "nyny.c", "34" ),
           REGISTER_DRIVERSECTION( "offtwall.c", "495" ),
           REGISTER_DRIVERSECTION( "ohmygod.c", "496" ),
           REGISTER_DRIVERSECTION( "ojankohs.c", "497" ),
           REGISTER_DRIVERSECTION( "olibochu.c", "498" ),
           REGISTER_DRIVERSECTION( "omegaf.c", "499" ),
           REGISTER_DRIVERSECTION( "omegrace.c", "500" ),
           REGISTER_DRIVERSECTION( "oneshot.c", "501" ),
           REGISTER_DRIVERSECTION( "opwolf.c", "10" ),
           REGISTER_DRIVERSECTION( "orbit.c", "503" ),
           REGISTER_DRIVERSECTION( "othldrby.c", "504" ),
           REGISTER_DRIVERSECTION( "othunder.c", "505" ),
           REGISTER_DRIVERSECTION( "outrun.c", "3" ),
           REGISTER_DRIVERSECTION( "overdriv.c", "507" ),
           REGISTER_DRIVERSECTION( "pacland.c", "508" ),
           REGISTER_DRIVERSECTION( "pacman.c", "8" ),
           REGISTER_DRIVERSECTION( "pandoras.c", "510" ),
           REGISTER_DRIVERSECTION( "paradise.c", "511" ),
           REGISTER_DRIVERSECTION( "parodius.c", "512" ),
           REGISTER_DRIVERSECTION( "pass.c", "513" ),
           REGISTER_DRIVERSECTION( "pastelgl.c", "514" ),
           REGISTER_DRIVERSECTION( "pbaction.c", "515" ),
           REGISTER_DRIVERSECTION( "pbillian.c", "516" ),
           REGISTER_DRIVERSECTION( "pcktgal.c", "517" ),
           REGISTER_DRIVERSECTION( "pengo.c", "8" ),
           REGISTER_DRIVERSECTION( "pgm.c", "519" ),
           REGISTER_DRIVERSECTION( "phoenix.c", "8" ),
           REGISTER_DRIVERSECTION( "pingpong.c", "521" ),
           REGISTER_DRIVERSECTION( "pipedrm.c", "22" ),
           REGISTER_DRIVERSECTION( "pirates.c", "523" ),
           REGISTER_DRIVERSECTION( "pitnrun.c", "524" ),
           REGISTER_DRIVERSECTION( "pkunwar.c", "13" ),
           REGISTER_DRIVERSECTION( "playch10.c", "526" ),
           REGISTER_DRIVERSECTION( "playmark.c", "33" ),
           REGISTER_DRIVERSECTION( "plygonet.c", "528" ),
           REGISTER_DRIVERSECTION( "polepos.c", "529" ),
           REGISTER_DRIVERSECTION( "policetr.c", "530" ),
           REGISTER_DRIVERSECTION( "polyplay.c", "531" ),
           REGISTER_DRIVERSECTION( "poolshrk.c", "533" ),
           REGISTER_DRIVERSECTION( "pooyan.c", "16" ),
           REGISTER_DRIVERSECTION( "popeye.c", "535" ),
           REGISTER_DRIVERSECTION( "popper.c", "536" ),
           REGISTER_DRIVERSECTION( "portrait.c", "537" ),
           REGISTER_DRIVERSECTION( "powerins.c", "538" ),
           REGISTER_DRIVERSECTION( "prehisle.c", "539" ),
           REGISTER_DRIVERSECTION( "psikyo.c", "540" ),
           REGISTER_DRIVERSECTION( "psikyo4.c", "541" ),
           REGISTER_DRIVERSECTION( "psikyosh.c", "542" ),
           REGISTER_DRIVERSECTION( "psychic5.c", "543" ),
           REGISTER_DRIVERSECTION( "punchout.c", "544" ),
           REGISTER_DRIVERSECTION( "pushman.c", "545" ),
           REGISTER_DRIVERSECTION( "qix.c", "546" ),
           REGISTER_DRIVERSECTION( "quantum.c", "547" ),
           REGISTER_DRIVERSECTION( "quizdna.c", "548" ),
           REGISTER_DRIVERSECTION( "quizpani.c", "549" ),
           REGISTER_DRIVERSECTION( "r2dtank.c", "550" ),
           REGISTER_DRIVERSECTION( "rabbit.c", "551" ),
           REGISTER_DRIVERSECTION( "raiden.c", "552" ),
           REGISTER_DRIVERSECTION( "raiden2.c", "553" ),
           REGISTER_DRIVERSECTION( "raiders5.c", "554" ),
           REGISTER_DRIVERSECTION( "rainbow.c", "10" ),
           REGISTER_DRIVERSECTION( "rallyx.c", "16" ),
           REGISTER_DRIVERSECTION( "rampart.c", "9" ),
           REGISTER_DRIVERSECTION( "rastan.c", "10" ),
           REGISTER_DRIVERSECTION( "realbrk.c", "559" ),
           REGISTER_DRIVERSECTION( "redalert.c", "560" ),
           REGISTER_DRIVERSECTION( "redclash.c", "561" ),
           REGISTER_DRIVERSECTION( "relief.c", "562" ),
           REGISTER_DRIVERSECTION( "renegade.c", "563" ),
           REGISTER_DRIVERSECTION( "retofinv.c", "564" ),
           REGISTER_DRIVERSECTION( "rmhaihai.c", "565" ),
           REGISTER_DRIVERSECTION( "rockola.c", "566" ),
           REGISTER_DRIVERSECTION( "rockrage.c", "567" ),
           REGISTER_DRIVERSECTION( "rocnrope.c", "16" ),
           REGISTER_DRIVERSECTION( "rohga.c", "569" ),
           REGISTER_DRIVERSECTION( "rollerg.c", "570" ),
           REGISTER_DRIVERSECTION( "rollrace.c", "27" ),
           REGISTER_DRIVERSECTION( "rotaryf.c", "30" ),
           REGISTER_DRIVERSECTION( "route16.c", "573" ),
           REGISTER_DRIVERSECTION( "royalmah.c", "574" ),
           REGISTER_DRIVERSECTION( "rpunch.c", "575" ),
           REGISTER_DRIVERSECTION( "runaway.c", "576" ),
           REGISTER_DRIVERSECTION( "rungun.c", "577" ),
           REGISTER_DRIVERSECTION( "safarir.c", "578" ),
           REGISTER_DRIVERSECTION( "sauro.c", "579" ),
           REGISTER_DRIVERSECTION( "sbasketb.c", "20" ),
           REGISTER_DRIVERSECTION( "sbowling.c", "581" ),
           REGISTER_DRIVERSECTION( "sbrkout.c", "582" ),
           REGISTER_DRIVERSECTION( "sbugger.c", "583" ),
           REGISTER_DRIVERSECTION( "scobra.c", "8" ),
           REGISTER_DRIVERSECTION( "scramble.c", "8" ),
           REGISTER_DRIVERSECTION( "scregg.c", "32" ),
           REGISTER_DRIVERSECTION( "seattle.c", "587" ),
           REGISTER_DRIVERSECTION( "sega.c", "25" ),
           REGISTER_DRIVERSECTION( "segac2.c", "3" ),
           REGISTER_DRIVERSECTION( "segar.c", "25" ),
           REGISTER_DRIVERSECTION( "segasyse.c", "3" ),
           REGISTER_DRIVERSECTION( "seicross.c", "592" ),
           REGISTER_DRIVERSECTION( "sengokmj.c", "593" ),
           REGISTER_DRIVERSECTION( "senjyo.c", "594" ),
           REGISTER_DRIVERSECTION( "seta.c", "595" ),
           REGISTER_DRIVERSECTION( "seta2.c", "596" ),
           REGISTER_DRIVERSECTION( "sf1.c", "597" ),
           REGISTER_DRIVERSECTION( "sg1000a.c", "598" ),
           REGISTER_DRIVERSECTION( "sgladiat.c", "7" ),
           REGISTER_DRIVERSECTION( "shadfrce.c", "600" ),
           REGISTER_DRIVERSECTION( "shangha3.c", "601" ),
           REGISTER_DRIVERSECTION( "shanghai.c", "602" ),
           REGISTER_DRIVERSECTION( "shangkid.c", "603" ),
           REGISTER_DRIVERSECTION( "shaolins.c", "604" ),
           REGISTER_DRIVERSECTION( "sharrier.c", "3" ),
           REGISTER_DRIVERSECTION( "shisen.c", "18" ),
           REGISTER_DRIVERSECTION( "shootout.c", "607" ),
           REGISTER_DRIVERSECTION( "shougi.c", "608" ),
           REGISTER_DRIVERSECTION( "shuuz.c", "609" ),
           REGISTER_DRIVERSECTION( "sidearms.c", "610" ),
           REGISTER_DRIVERSECTION( "sidepckt.c", "611" ),
           REGISTER_DRIVERSECTION( "silkroad.c", "612" ),
           REGISTER_DRIVERSECTION( "simpsons.c", "613" ),
           REGISTER_DRIVERSECTION( "skullxbo.c", "614" ),
           REGISTER_DRIVERSECTION( "skyarmy.c", "615" ),
           REGISTER_DRIVERSECTION( "skychut.c", "616" ),
           REGISTER_DRIVERSECTION( "skydiver.c", "617" ),
           REGISTER_DRIVERSECTION( "skyfox.c", "618" ),
           REGISTER_DRIVERSECTION( "skykid.c", "619" ),
           REGISTER_DRIVERSECTION( "skyraid.c", "620" ),
           REGISTER_DRIVERSECTION( "slapfght.c", "621" ),
           REGISTER_DRIVERSECTION( "slapshot.c", "622" ),
           REGISTER_DRIVERSECTION( "snk.c", "7" ),
           REGISTER_DRIVERSECTION( "snk68.c", "624" ),
           REGISTER_DRIVERSECTION( "snowbros.c", "625" ),
           REGISTER_DRIVERSECTION( "solomon.c", "626" ),
           REGISTER_DRIVERSECTION( "sonson.c", "627" ),
           REGISTER_DRIVERSECTION( "spacefb.c", "628" ),
           REGISTER_DRIVERSECTION( "spbactn.c", "629" ),
           REGISTER_DRIVERSECTION( "spcforce.c", "630" ),
           REGISTER_DRIVERSECTION( "spdbuggy.c", "631" ),
           REGISTER_DRIVERSECTION( "spdodgeb.c", "632" ),
           REGISTER_DRIVERSECTION( "speedatk.c", "633" ),
           REGISTER_DRIVERSECTION( "speedbal.c", "634" ),
           REGISTER_DRIVERSECTION( "speedspn.c", "635" ),
           REGISTER_DRIVERSECTION( "spiders.c", "34" ),
           REGISTER_DRIVERSECTION( "splash.c", "637" ),
           REGISTER_DRIVERSECTION( "sprcros2.c", "638" ),
           REGISTER_DRIVERSECTION( "sprint2.c", "639" ),
           REGISTER_DRIVERSECTION( "sprint4.c", "640" ),
           REGISTER_DRIVERSECTION( "sprint8.c", "641" ),
           REGISTER_DRIVERSECTION( "spy.c", "642" ),
           REGISTER_DRIVERSECTION( "srmp2.c", "643" ),
           REGISTER_DRIVERSECTION( "srumbler.c", "644" ),
           REGISTER_DRIVERSECTION( "sshangha.c", "645" ),
           REGISTER_DRIVERSECTION( "sslam.c", "33" ),
           REGISTER_DRIVERSECTION( "ssozumo.c", "647" ),
           REGISTER_DRIVERSECTION( "sspeedr.c", "648" ),
           REGISTER_DRIVERSECTION( "ssrj.c", "649" ),
           REGISTER_DRIVERSECTION( "ssv.c", "650" ),
           REGISTER_DRIVERSECTION( "stactics.c", "651" ),
           REGISTER_DRIVERSECTION( "stadhero.c", "652" ),
           REGISTER_DRIVERSECTION( "starcrus.c", "653" ),
           REGISTER_DRIVERSECTION( "starfire.c", "654" ),
           REGISTER_DRIVERSECTION( "starshp1.c", "655" ),
           REGISTER_DRIVERSECTION( "starwars.c", "656" ),
           REGISTER_DRIVERSECTION( "statriv2.c", "657" ),
           REGISTER_DRIVERSECTION( "stfight.c", "658" ),
           REGISTER_DRIVERSECTION( "stlforce.c", "659" ),
           REGISTER_DRIVERSECTION( "strnskil.c", "660" ),
           REGISTER_DRIVERSECTION( "strvmstr.c", "661" ),
           REGISTER_DRIVERSECTION( "stv.c", "662" ),
           REGISTER_DRIVERSECTION( "stvhacks.c", "663" ),
           REGISTER_DRIVERSECTION( "subs.c", "664" ),
           REGISTER_DRIVERSECTION( "suna16.c", "665" ),
           REGISTER_DRIVERSECTION( "suna8.c", "666" ),
           REGISTER_DRIVERSECTION( "supbtime.c", "667" ),
           REGISTER_DRIVERSECTION( "supdrapo.c", "668" ),
           REGISTER_DRIVERSECTION( "superchs.c", "21" ),
           REGISTER_DRIVERSECTION( "superqix.c", "670" ),
           REGISTER_DRIVERSECTION( "supertnk.c", "671" ),
           REGISTER_DRIVERSECTION( "suprloco.c", "672" ),
           REGISTER_DRIVERSECTION( "suprnova.c", "673" ),
           REGISTER_DRIVERSECTION( "suprslam.c", "674" ),
           REGISTER_DRIVERSECTION( "surpratk.c", "675" ),
           REGISTER_DRIVERSECTION( "system1.c", "3" ),
           REGISTER_DRIVERSECTION( "system16.c", "3" ),
           REGISTER_DRIVERSECTION( "system18.c", "3" ),
           REGISTER_DRIVERSECTION( "system24.c", "3" ),
           REGISTER_DRIVERSECTION( "system32.c", "3" ),
           REGISTER_DRIVERSECTION( "tagteam.c", "681" ),
           REGISTER_DRIVERSECTION( "tail2nos.c", "682" ),
           REGISTER_DRIVERSECTION( "taito_b.c", "683" ),
           REGISTER_DRIVERSECTION( "taito_f2.c", "684" ),
           REGISTER_DRIVERSECTION( "taito_f3.c", "21" ),
           REGISTER_DRIVERSECTION( "taito_h.c", "686" ),
           REGISTER_DRIVERSECTION( "taito_l.c", "687" ),
           REGISTER_DRIVERSECTION( "taito_x.c", "688" ),
           REGISTER_DRIVERSECTION( "taito_z.c", "689" ),
           REGISTER_DRIVERSECTION( "taitoair.c", "690" ),
           REGISTER_DRIVERSECTION( "taitosj.c", "691" ),
           REGISTER_DRIVERSECTION( "tankbatt.c", "692" ),
           REGISTER_DRIVERSECTION( "tankbust.c", "693" ),
           REGISTER_DRIVERSECTION( "taotaido.c", "694" ),
           REGISTER_DRIVERSECTION( "targeth.c", "695" ),
           REGISTER_DRIVERSECTION( "taxidrvr.c", "696" ),
           REGISTER_DRIVERSECTION( "tbowl.c", "697" ),
           REGISTER_DRIVERSECTION( "tceptor.c", "698" ),
           REGISTER_DRIVERSECTION( "tecmo.c", "699" ),
           REGISTER_DRIVERSECTION( "tecmo16.c", "700" ),
           REGISTER_DRIVERSECTION( "tecmosys.c", "701" ),
           REGISTER_DRIVERSECTION( "tehkanwc.c", "702" ),
           REGISTER_DRIVERSECTION( "tempest.c", "703" ),
           REGISTER_DRIVERSECTION( "terracre.c", "704" ),
           REGISTER_DRIVERSECTION( "tetrisp2.c", "28" ),
           REGISTER_DRIVERSECTION( "thedeep.c", "706" ),
           REGISTER_DRIVERSECTION( "thepit.c", "707" ),
           REGISTER_DRIVERSECTION( "thief.c", "708" ),
           REGISTER_DRIVERSECTION( "thoop2.c", "709" ),
           REGISTER_DRIVERSECTION( "thunderj.c", "36" ),
           REGISTER_DRIVERSECTION( "thunderx.c", "711" ),
           REGISTER_DRIVERSECTION( "tickee.c", "712" ),
           REGISTER_DRIVERSECTION( "tigeroad.c", "713" ),
           REGISTER_DRIVERSECTION( "timelimt.c", "714" ),
           REGISTER_DRIVERSECTION( "timeplt.c", "16" ),
           REGISTER_DRIVERSECTION( "tmnt.c", "716" ),
           REGISTER_DRIVERSECTION( "tnzs.c", "717" ),
           REGISTER_DRIVERSECTION( "toaplan1.c", "718" ),
           REGISTER_DRIVERSECTION( "toaplan2.c", "719" ),
           REGISTER_DRIVERSECTION( "toki.c", "720" ),
           REGISTER_DRIVERSECTION( "toobin.c", "721" ),
           REGISTER_DRIVERSECTION( "topspeed.c", "10" ),
           REGISTER_DRIVERSECTION( "toratora.c", "723" ),
           REGISTER_DRIVERSECTION( "tourtabl.c", "724" ),
           REGISTER_DRIVERSECTION( "toypop.c", "725" ),
           REGISTER_DRIVERSECTION( "tp84.c", "726" ),
           REGISTER_DRIVERSECTION( "trackfld.c", "20" ),
           REGISTER_DRIVERSECTION( "travrusa.c", "728" ),
           REGISTER_DRIVERSECTION( "triplhnt.c", "729" ),
           REGISTER_DRIVERSECTION( "troangel.c", "730" ),
           REGISTER_DRIVERSECTION( "truco.c", "731" ),
           REGISTER_DRIVERSECTION( "tryout.c", "732" ),
           REGISTER_DRIVERSECTION( "tsamurai.c", "733" ),
           REGISTER_DRIVERSECTION( "ttmahjng.c", "734" ),
           REGISTER_DRIVERSECTION( "tubep.c", "735" ),
           REGISTER_DRIVERSECTION( "tugboat.c", "736" ),
           REGISTER_DRIVERSECTION( "tumblep.c", "737" ),
           REGISTER_DRIVERSECTION( "tunhunt.c", "738" ),
           REGISTER_DRIVERSECTION( "turbo.c", "739" ),
           REGISTER_DRIVERSECTION( "tutankhm.c", "16" ),
           REGISTER_DRIVERSECTION( "twin16.c", "741" ),
           REGISTER_DRIVERSECTION( "twincobr.c", "5" ),
           REGISTER_DRIVERSECTION( "ultraman.c", "743" ),
           REGISTER_DRIVERSECTION( "ultratnk.c", "744" ),
           REGISTER_DRIVERSECTION( "undrfire.c", "21" ),
           REGISTER_DRIVERSECTION( "unico.c", "746" ),
           REGISTER_DRIVERSECTION( "usgames.c", "747" ),
           REGISTER_DRIVERSECTION( "vamphalf.c", "748" ),
           REGISTER_DRIVERSECTION( "vaportra.c", "749" ),
           REGISTER_DRIVERSECTION( "vastar.c", "750" ),
           REGISTER_DRIVERSECTION( "vball.c", "751" ),
           REGISTER_DRIVERSECTION( "vendetta.c", "752" ),
           REGISTER_DRIVERSECTION( "vicdual.c", "753" ),
           REGISTER_DRIVERSECTION( "victory.c", "17" ),
           REGISTER_DRIVERSECTION( "videopin.c", "755" ),
           REGISTER_DRIVERSECTION( "vigilant.c", "18" ),
           REGISTER_DRIVERSECTION( "vindictr.c", "757" ),
           REGISTER_DRIVERSECTION( "vmetal.c", "758" ),
           REGISTER_DRIVERSECTION( "volfied.c", "759" ),
           REGISTER_DRIVERSECTION( "vsnes.c", "760" ),
           REGISTER_DRIVERSECTION( "vulgus.c", "761" ),
           REGISTER_DRIVERSECTION( "wallc.c", "762" ),
           REGISTER_DRIVERSECTION( "wardner.c", "5" ),
           REGISTER_DRIVERSECTION( "warpwarp.c", "764" ),
           REGISTER_DRIVERSECTION( "warriorb.c", "765" ),
           REGISTER_DRIVERSECTION( "wc90.c", "766" ),
           REGISTER_DRIVERSECTION( "wc90b.c", "767" ),
           REGISTER_DRIVERSECTION( "wecleman.c", "768" ),
           REGISTER_DRIVERSECTION( "welltris.c", "769" ),
           REGISTER_DRIVERSECTION( "wgp.c", "770" ),
           REGISTER_DRIVERSECTION( "williams.c", "4" ),
           REGISTER_DRIVERSECTION( "wilytowr.c", "772" ),
           REGISTER_DRIVERSECTION( "wiping.c", "29" ),
           REGISTER_DRIVERSECTION( "wiz.c", "27" ),
           REGISTER_DRIVERSECTION( "wolfpack.c", "775" ),
           REGISTER_DRIVERSECTION( "wrally.c", "776" ),
           REGISTER_DRIVERSECTION( "wwfsstar.c", "777" ),
           REGISTER_DRIVERSECTION( "wwfwfest.c", "778" ),
           REGISTER_DRIVERSECTION( "xain.c", "779" ),
           REGISTER_DRIVERSECTION( "xevious.c", "780" ),
           REGISTER_DRIVERSECTION( "xexex.c", "781" ),
           REGISTER_DRIVERSECTION( "xmen.c", "782" ),
           REGISTER_DRIVERSECTION( "xorworld.c", "783" ),
           REGISTER_DRIVERSECTION( "xxmissio.c", "784" ),
           REGISTER_DRIVERSECTION( "xybots.c", "785" ),
           REGISTER_DRIVERSECTION( "xyonix.c", "786" ),
           REGISTER_DRIVERSECTION( "yamato.c", "8" ),
           REGISTER_DRIVERSECTION( "yard.c", "6" ),
           REGISTER_DRIVERSECTION( "yiear.c", "20" ),
           REGISTER_DRIVERSECTION( "yumefuda.c", "790" ),
           REGISTER_DRIVERSECTION( "yunsun16.c", "791" ),
           REGISTER_DRIVERSECTION( "yunsung8.c", "792" ),
           REGISTER_DRIVERSECTION( "zac2650.c", "793" ),
           REGISTER_DRIVERSECTION( "zaccaria.c", "794" ),
           REGISTER_DRIVERSECTION( "zaxxon.c", "26" ),
           REGISTER_DRIVERSECTION( "zerozone.c", "796" ),
           REGISTER_DRIVERSECTION( "zn.c", "797" ),
           REGISTER_DRIVERSECTION( "zodiack.c", "11" ) };


//-------------------------------------------------------------
//	IsDriverClone
//-------------------------------------------------------------
inline BOOL IsDriverClone( const char *driverName )
{
  return( !strcmp( driverName, "cps2.c" ) ||
        !strcmp( driverName, "namcona1.c" ) ||
        !strcmp( driverName, "namconb1.c" ) ||
        !strcmp( driverName, "namcond1.c" ) ||
        !strcmp( driverName, "namcos1.c" ) ||
        !strcmp( driverName, "namcos2.c" ) ||
        !strcmp( driverName, "namcos21.c" ) ||
        !strcmp( driverName, "namcos22.c" ) ||
        !strcmp( driverName, "namcos86.c" ) ||
        !strcmp( driverName, "namcos11.c" ) ||
        !strcmp( driverName, "system1.c" ) ||
        !strcmp( driverName, "system16.c" ) ||
        !strcmp( driverName, "system18.c" ) ||
        !strcmp( driverName, "system24.c" ) ||
        !strcmp( driverName, "system32.c" ) ||
        !strcmp( driverName, "aburner.c" ) ||
        !strcmp( driverName, "sharrier.c" ) ||
        !strcmp( driverName, "outrun.c" ) ||
        !strcmp( driverName, "segasyse.c" ) ||
        !strcmp( driverName, "segac2.c" ) ||
        !strcmp( driverName, "mcr2.c" ) ||
        !strcmp( driverName, "mcr3.c" ) ||
        !strcmp( driverName, "mcr68.c" ) ||
        !strcmp( driverName, "williams.c" ) ||
        !strcmp( driverName, "midyunit.c" ) ||
        !strcmp( driverName, "midtunit.c" ) ||
        !strcmp( driverName, "midwunit.c" ) ||
        !strcmp( driverName, "midvunit.c" ) ||
        !strcmp( driverName, "midxunit.c" ) ||
        !strcmp( driverName, "twincobr.c" ) ||
        !strcmp( driverName, "yard.c" ) ||
        !strcmp( driverName, "hal21.c" ) ||
        !strcmp( driverName, "marvins.c" ) ||
        !strcmp( driverName, "sgladiat.c" ) ||
        !strcmp( driverName, "scramble.c" ) ||
        !strcmp( driverName, "scobra.c" ) ||
        !strcmp( driverName, "amidar.c" ) ||
        !strcmp( driverName, "frogger.c" ) ||
        !strcmp( driverName, "pacman.c" ) ||
        !strcmp( driverName, "pengo.c" ) ||
        !strcmp( driverName, "cclimber.c" ) ||
        !strcmp( driverName, "dkong.c" ) ||
        !strcmp( driverName, "yamato.c" ) ||
        !strcmp( driverName, "phoenix.c" ) ||
        !strcmp( driverName, "epos.c" ) ||
        !strcmp( driverName, "arcadecl.c" ) ||
        !strcmp( driverName, "asuka.c" ) ||
        !strcmp( driverName, "opwolf.c" ) ||
        !strcmp( driverName, "rainbow.c" ) ||
        !strcmp( driverName, "topspeed.c" ) ||
        !strcmp( driverName, "marineb.c" ) ||
        !strcmp( driverName, "zodiack.c" ) ||
        !strcmp( driverName, "bwidow.c" ) ||
        !strcmp( driverName, "pkunwar.c" ) ||
        !strcmp( driverName, "exterm.c" ) ||
        !strcmp( driverName, "cischeat.c" ) ||
        !strcmp( driverName, "timeplt.c" ) ||
        !strcmp( driverName, "locomotn.c" ) ||
        !strcmp( driverName, "tutankhm.c" ) ||
        !strcmp( driverName, "pooyan.c" ) ||
        !strcmp( driverName, "rocnrope.c" ) ||
        !strcmp( driverName, "junofrst.c" ) ||
        !strcmp( driverName, "victory.c" ) ||
        !strcmp( driverName, "m90.c" ) ||
        !strcmp( driverName, "vigilant.c" ) ||
        !strcmp( driverName, "shisen.c" ) ||
        !strcmp( driverName, "ataxx.c" ) ||
        !strcmp( driverName, "hyperspt.c" ) ||
        !strcmp( driverName, "yiear.c" ) ||
        !strcmp( driverName, "sbasketb.c" ) ||
        !strcmp( driverName, "superchs.c" ) ||
        !strcmp( driverName, "groundfx.c" ) ||
        !strcmp( driverName, "gunbustr.c" ) ||
        !strcmp( driverName, "undrfire.c" ) ||
        !strcmp( driverName, "pipedrm.c" ) ||
        !strcmp( driverName, "mystwarr.c" ) ||
        !strcmp( driverName, "sega.c" ) ||
        !strcmp( driverName, "congo.c" ) ||
        !strcmp( driverName, "rollrace.c" ) ||
        !strcmp( driverName, "tetrisp2.c" ) ||
        !strcmp( driverName, "clshroad.c" ) ||
        !strcmp( driverName, "rotaryf.c" ) ||
        !strcmp( driverName, "circus.c" ) ||
        !strcmp( driverName, "40love.c" ) ||
        !strcmp( driverName, "scregg.c" ) ||
        !strcmp( driverName, "sslam.c" ) ||
        !strcmp( driverName, "spiders.c" ) ||
        !strcmp( driverName, "chinagat.c" ) ||
        !strcmp( driverName, "eprom.c" ) );
}

#ifdef _DEBUG
//-------------------------------------------------------------
//	CheckDriverSectionRAM
//-------------------------------------------------------------
void CheckDriverSectionRAM( void )
{
  DWORD total = 0;

	const driverSectionRegistration_t *entry = (const driverSectionRegistration_t *)g_driverSectionRegistry;
	for( int i = 0; i < NUM_DRIVERSECTIONS; ++entry, ++i )
	{
      // Only test families once (all but the first member are skipped)
		if( !IsDriverClone( entry->m_driverName ) )
		{
			HANDLE h = XGetSectionHandle( entry->m_sectionName );
			if( h != INVALID_HANDLE_VALUE )
			{
				UINT32 sz = XGetSectionSize( h );
				PRINTMSG(( T_INFO, "Driver %s %lu", entry->m_driverName, sz ));
				total += sz;
			}
			else
				PRINTMSG(( T_ERROR, "Invalid section %s for file %s!", entry->m_sectionName, entry->m_driverName ));
		}
	}
  PRINTMSG(( T_INFO, "Total %lu bytes\n", total ));
}
#endif




//-------------------------------------------------------------
//	LoadDriverSections
//-------------------------------------------------------------
BOOL LoadDriverSections( void )
{
	const driverSectionRegistration_t *entry = (const driverSectionRegistration_t *)g_driverSectionRegistry;
	for( int i = 0; i < NUM_DRIVERSECTIONS; ++entry, ++i )
	{
      // Only load families once (all but the first member are skipped)
		if( !IsDriverClone( entry->m_driverName ) )
		{
			if( !XLoadSection( entry->m_sectionName ) )
			{
				PRINTMSG(( T_ERROR, "XLoadSection %s for driver %s failed! 0x%X", entry->m_sectionName, entry->m_driverName, GetLastError() ));
				return FALSE;
			}
		}
  }
  return TRUE;
}

//-------------------------------------------------------------
//	UnloadDriverSections
//-------------------------------------------------------------
BOOL UnloadDriverSections( void )
{
	const driverSectionRegistration_t *entry = (const driverSectionRegistration_t *)g_driverSectionRegistry;
	for( int i = 0; i < NUM_DRIVERSECTIONS; ++entry, ++i )
	{
      // Only unload families once (all but the first member are skipped)
		if( !IsDriverClone( entry->m_driverName ) )
		{
		  if( !XFreeSection( entry->m_sectionName ) )
			{
				PRINTMSG(( T_ERROR, "XFreeSection %s for driver %s failed! 0x%X", entry->m_sectionName, entry->m_driverName, GetLastError() ));
			}
		}
	}

	return TRUE;
}

//-------------------------------------------------------------
//	LoadDriverSectionByName
//-------------------------------------------------------------
BOOL LoadDriverSectionByName( const char *driverFileName )
{
	const driverSectionRegistration_t *entry = (const driverSectionRegistration_t *)g_driverSectionRegistry;
	for( int i = 0; i < NUM_DRIVERSECTIONS; ++entry, ++i )
	{
		if( !strcmp( entry->m_driverName, driverFileName ) )
		{
			PRINTMSG(( T_INFO, "Load section %s for driver %s\n", entry->m_sectionName, entry->m_driverName ));
			if( !XLoadSection( entry->m_sectionName ) )
			{
				PRINTMSG(( T_ERROR, "XLoadSection %s for driver %s failed! 0x%X", entry->m_sectionName, entry->m_driverName, GetLastError() ));
				return FALSE;
			}

			return TRUE;
		}
	}

	PRINTMSG(( T_INFO, "No section registered for driver %s!\n", driverFileName ));
  return FALSE;
}


//-------------------------------------------------------------
//	UnloadDriverSectionByName
//-------------------------------------------------------------
BOOL UnloadDriverSectionByName( const char *driverFileName )
{
	const driverSectionRegistration_t *entry = (const driverSectionRegistration_t *)g_driverSectionRegistry;
	for( int i = 0; i < NUM_DRIVERSECTIONS; ++entry, ++i )
	{
		if( !strcmp( entry->m_driverName, driverFileName ) )
		{
			PRINTMSG(( T_INFO, "Free section %s for driver %s\n", entry->m_sectionName, entry->m_driverName ));
			if( !XFreeSection( entry->m_sectionName ) )
			{
				PRINTMSG(( T_ERROR, "XFreeSection %s for driver %s failed! 0x%X", entry->m_sectionName, entry->m_driverName, GetLastError() ));
				return FALSE;
			}

			return TRUE;
		}
	}

	PRINTMSG(( T_INFO, "No section registered for driver %s!\n", driverFileName ));
  return FALSE;
}

#pragma code_seg()			// End of DRVSNIZE
#pragma data_seg()
#pragma bss_seg()
#pragma const_seg()



  //--- CPU Functions -----------------------------------------------

#pragma code_seg( "CPUCSNZE" )
#pragma data_seg( "CPUDSNZE" )
#pragma const_seg( "CPUKSNZE" )
#pragma bss_seg( "CPUBSNZE" )
#pragma comment(linker, "/merge:CPUCSNZE=CPUSNIZE")
#pragma comment(linker, "/merge:CPUDSNZE=CPUSNIZE")
#pragma comment(linker, "/merge:CPUKSNZE=CPUSNIZE")
#pragma comment(linker, "/merge:CPUBSNZE=CPUSNIZE")

#ifdef _DEBUG
//-------------------------------------------------------------
//	CheckCPUSectionRAM
//-------------------------------------------------------------
void CheckCPUSectionRAM( void )
{
  DWORD total = 0;
  std::map< UINT32, std::string >::iterator i = g_CPUIDToSectionMap.begin();
  for( ; i != g_CPUIDToSectionMap.end(); ++i )
  {
    HANDLE h = XGetSectionHandle( (*i).second.c_str() );
    if( h != INVALID_HANDLE_VALUE )
    {
      UINT32 sz = XGetSectionSize( h );
      PRINTMSG(( T_INFO, "CPU%lu %lu", (*i).first, sz ));
      total += sz;
    }
    else
      PRINTMSG(( T_ERROR, "Invalid section %s for CPU%lu!", (*i).second.c_str(), (*i).first ));
  }
  PRINTMSG(( T_INFO, "Total %lu bytes\n", total ));
}
#endif


//-------------------------------------------------------------
//	RegisterSectionID
//-------------------------------------------------------------
static void RegisterSectionID( UINT32 CPUID, const char *DataSectionName )
{
    // Add the section name to the map
  g_CPUIDToSectionMap[ CPUID ] = DataSectionName;
}


//-------------------------------------------------------------
//	LoadCPUSectionByID
//-------------------------------------------------------------
BOOL LoadCPUSectionByID( UINT32 CPUID )
{
  std::map< UINT32, std::string >::iterator i = g_CPUIDToSectionMap.find( CPUID );
  if( i == g_CPUIDToSectionMap.end() )
    return FALSE;
  void *addr;
  PRINTMSG(( T_INFO, "Load section CPU%lu, ID %s\n", CPUID, (*i).second.c_str() ));
  addr = XLoadSection( (*i).second.c_str() );
  if( !addr )
  {
    UINT32 lastErr = GetLastError();
    PRINTMSG(( T_ERROR, "XLoadSection failed for section %s! 0x%X\r\n", (*i).second.c_str(), lastErr ));
  }
  return TRUE;
}


//-------------------------------------------------------------
//	UnloadCPUSectionByID
//-------------------------------------------------------------
BOOL UnloadCPUSectionByID( UINT32 CPUID )
{
  std::map< UINT32, std::string >::iterator i = g_CPUIDToSectionMap.find( CPUID );
  if( i == g_CPUIDToSectionMap.end() )
    return FALSE;
  return XFreeSection( (*i).second.c_str() );
}


//-------------------------------------------------------------
//	LoadCPUSections
//-------------------------------------------------------------
BOOL LoadCPUSections( void )
{
  std::map< UINT32, std::string >::iterator i = g_CPUIDToSectionMap.begin();
  for( ; i != g_CPUIDToSectionMap.end(); ++i )
  {
    if( !XLoadSection( (*i).second.c_str() ) )
    {
      PRINTMSG(( T_ERROR, "Failed to load section %s!", (*i).second.c_str() ));
      //return FALSE;
    }
  }
  return TRUE;
}


//-------------------------------------------------------------
//	UnloadCPUSections
//-------------------------------------------------------------
BOOL UnloadCPUSections( void )
{
  std::map< UINT32, std::string >::iterator i = g_CPUIDToSectionMap.begin();
  for( ; i != g_CPUIDToSectionMap.end(); ++i )
  {
      // Only unload families once (all but the first member are skipped)
    if( (*i).first == CPU_M65C02 ||
        (*i).first == CPU_M6510 ||
        (*i).first == CPU_N2A03 ||
        (*i).first == CPU_DECO16 ||
        (*i).first == CPU_I186 ||
        (*i).first == CPU_V30 ||
        (*i).first == CPU_V33 ||
        (*i).first == CPU_V70 ||
        (*i).first == CPU_I8039 ||
        (*i).first == CPU_I8048 ||
        (*i).first == CPU_N7751 ||
        (*i).first == CPU_M6801 ||
        (*i).first == CPU_M6802 ||
        (*i).first == CPU_M6803 ||
        (*i).first == CPU_M6808 ||
        (*i).first == CPU_HD63701 ||
        (*i).first == CPU_NSC8105 ||
        (*i).first == CPU_M68705 ||
        (*i).first == CPU_HD63705 ||
        (*i).first == CPU_M68010 ||
        (*i).first == CPU_M68020 ||
        (*i).first == CPU_M68EC020 ||
        (*i).first == CPU_TMS34020 ||
        (*i).first == CPU_TMS9995 ||
        (*i).first == CPU_ADSP2101 ||
        (*i).first == CPU_ADSP2105 ||
        (*i).first == CPU_ADSP2115 ||
        (*i).first == CPU_R3000BE ||
        (*i).first == CPU_R3000LE ||
        (*i).first == CPU_R4600BE ||
        (*i).first == CPU_R4600LE ||
        (*i).first == CPU_R5000BE ||
        (*i).first == CPU_R5000LE ||
        (*i).first == CPU_UPD7807 ||
        (*i).first == CPU_JAGUARDSP ||
        (*i).first == CPU_PIC16C55 ||
        (*i).first == CPU_PIC16C56 ||
        (*i).first == CPU_PIC16C57 ||
        (*i).first == CPU_PIC16C58 )
        continue;
    XFreeSection( (*i).second.c_str() );
  }
  return TRUE;
}


//-------------------------------------------------------------
//	RegisterCPUSectionNames
//-------------------------------------------------------------
static void RegisterCPUSectionNames( void )
{
  RegisterSectionID( CPU_ADSP2100, "CPU26" );
  RegisterSectionID( CPU_ADSP2101, "CPU26" );
  RegisterSectionID( CPU_ADSP2105, "CPU26" );
  RegisterSectionID( CPU_ADSP2115, "CPU26" );
  RegisterSectionID( CPU_ARM, "CPU31" );
  RegisterSectionID( CPU_ASAP, "CPU28" );
  RegisterSectionID( CPU_CCPU, "CPU25" );
  RegisterSectionID( CPU_DSP32C, "CPU33" );
  RegisterSectionID( CPU_E132XS, "CPU47" );
  RegisterSectionID( CPU_G65816, "CPU48" );
  RegisterSectionID( CPU_GENSYNC, "CPU49" );
  RegisterSectionID( CPU_H6280, "CPU5" );
  RegisterSectionID( CPU_HD6309, "CPU14" );
  RegisterSectionID( CPU_I8035, "CPU9" );
  RegisterSectionID( CPU_I8039, "CPU9" );
  RegisterSectionID( CPU_I8048, "CPU9" );
  RegisterSectionID( CPU_N7751, "CPU9" );
  RegisterSectionID( CPU_Z80, "CPU3" );
  RegisterSectionID( CPU_I86, "CPU6" );
  RegisterSectionID( CPU_I186, "CPU6" );
  RegisterSectionID( CPU_I8X41, "CPU10" );
  RegisterSectionID( CPU_JAGUARGPU, "CPU30" );
  RegisterSectionID( CPU_JAGUARDSP, "CPU30" );
  RegisterSectionID( CPU_KONAMI, "CPU15" );
  RegisterSectionID( CPU_M6502, "CPU4" );
  RegisterSectionID( CPU_M65C02, "CPU4" );
  RegisterSectionID( CPU_M6510, "CPU4" );
  RegisterSectionID( CPU_N2A03, "CPU4" );
  RegisterSectionID( CPU_DECO16, "CPU4" );
  RegisterSectionID( CPU_M6800, "CPU11" );
  RegisterSectionID( CPU_M6801, "CPU11" );
  RegisterSectionID( CPU_M6802, "CPU11" );
  RegisterSectionID( CPU_M6803, "CPU11" );
  RegisterSectionID( CPU_M6808, "CPU11" );
  RegisterSectionID( CPU_HD63701, "CPU11" );
  RegisterSectionID( CPU_NSC8105, "CPU11" );
  RegisterSectionID( CPU_M68000, "CPU16" );
  RegisterSectionID( CPU_M68010, "CPU16" );
  RegisterSectionID( CPU_M68020, "CPU16" );
  RegisterSectionID( CPU_M68EC020, "CPU16" );
  RegisterSectionID( CPU_M6805, "CPU12" );
  RegisterSectionID( CPU_M68705, "CPU12" );
  RegisterSectionID( CPU_HD63705, "CPU12" );
  RegisterSectionID( CPU_M6809, "CPU13" );
  RegisterSectionID( CPU_PSXCPU, "CPU27" );
  RegisterSectionID( CPU_R3000BE, "CPU27" );
  RegisterSectionID( CPU_R3000LE, "CPU27" );
  RegisterSectionID( CPU_R4600BE, "CPU27" );
  RegisterSectionID( CPU_R4600LE, "CPU27" );
  RegisterSectionID( CPU_R5000BE, "CPU27" );
  RegisterSectionID( CPU_R5000LE, "CPU27" );
  RegisterSectionID( CPU_V20, "CPU7" );
  RegisterSectionID( CPU_V30, "CPU7" );
  RegisterSectionID( CPU_V33, "CPU7" );
  RegisterSectionID( CPU_PIC16C54, "CPU34" );
  RegisterSectionID( CPU_PIC16C55, "CPU34" );
  RegisterSectionID( CPU_PIC16C56, "CPU34" );
  RegisterSectionID( CPU_PIC16C57, "CPU34" );
  RegisterSectionID( CPU_PIC16C58, "CPU34" );
  RegisterSectionID( CPU_S2650, "CPU18" );
  RegisterSectionID( CPU_SH2, "CPU32" );
  RegisterSectionID( CPU_SPC700, "CPU50" );
  RegisterSectionID( CPU_T11, "CPU17" );
  RegisterSectionID( CPU_TMS32010, "CPU22" );
  RegisterSectionID( CPU_TMS32025, "CPU23" );
  RegisterSectionID( CPU_TMS32031, "CPU24" );
  RegisterSectionID( CPU_TMS34010, "CPU19" );
  RegisterSectionID( CPU_TMS34020, "CPU19" );
  RegisterSectionID( CPU_TMS9980, "CPU20" );
  RegisterSectionID( CPU_TMS9995, "CPU20" );
  RegisterSectionID( CPU_UPD7810, "CPU29" );
  RegisterSectionID( CPU_UPD7807, "CPU29" );
  RegisterSectionID( CPU_V60, "CPU8" );
  RegisterSectionID( CPU_V70, "CPU8" );
  RegisterSectionID( CPU_Z180, "CPU2" );
  RegisterSectionID( CPU_Z80, "CPU1" );
  RegisterSectionID( CPU_Z8000, "CPU21" );
}
#pragma code_seg()
#pragma data_seg()
#pragma const_seg()
#pragma bss_seg()


} // End extern "C"


